// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.AccessToLogicMsg in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ============== Access -> Logic 方向 ==============
 */
public class AccessToLogicMsg(
  /**
   * 用户ID (从 Session 获取)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 0,
  )
  public val user_id: String = "",
  /**
   * 会话ID
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sessionId",
    schemaIndex = 1,
  )
  public val session_id: String = "",
  /**
   * Access 网关ID
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "gatewayId",
    schemaIndex = 2,
  )
  public val gateway_id: String = "",
  /**
   * 设备ID
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceId",
    schemaIndex = 3,
  )
  public val device_id: String = "",
  /**
   * 平台类型
   */
  @field:WireField(
    tag = 5,
    adapter = "com.sudooom.mahjong.common.proto.Platform#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val platform: Platform = Platform.PLATFORM_UNKNOWN,
  /**
   * 1. 用户业务消息
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.UserMessage#ADAPTER",
    jsonName = "userMessage",
    oneofName = "payload",
    schemaIndex = 5,
  )
  public val user_message: UserMessage? = null,
  /**
   * 2. 消息确认
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.MsgAck#ADAPTER",
    oneofName = "payload",
    schemaIndex = 6,
  )
  public val ack: MsgAck? = null,
  /**
   * 3. 系统指令
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.SystemCommand#ADAPTER",
    jsonName = "systemCmd",
    oneofName = "payload",
    schemaIndex = 7,
  )
  public val system_cmd: SystemCommand? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AccessToLogicMsg, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(user_message, ack, system_cmd) <= 1) {
      "At most one of user_message, ack, system_cmd may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AccessToLogicMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (user_id != other.user_id) return false
    if (session_id != other.session_id) return false
    if (gateway_id != other.gateway_id) return false
    if (device_id != other.device_id) return false
    if (platform != other.platform) return false
    if (user_message != other.user_message) return false
    if (ack != other.ack) return false
    if (system_cmd != other.system_cmd) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + session_id.hashCode()
      result = result * 37 + gateway_id.hashCode()
      result = result * 37 + device_id.hashCode()
      result = result * 37 + platform.hashCode()
      result = result * 37 + (user_message?.hashCode() ?: 0)
      result = result * 37 + (ack?.hashCode() ?: 0)
      result = result * 37 + (system_cmd?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """user_id=${sanitize(user_id)}"""
    result += """session_id=${sanitize(session_id)}"""
    result += """gateway_id=${sanitize(gateway_id)}"""
    result += """device_id=${sanitize(device_id)}"""
    result += """platform=$platform"""
    if (user_message != null) result += """user_message=$user_message"""
    if (ack != null) result += """ack=$ack"""
    if (system_cmd != null) result += """system_cmd=$system_cmd"""
    return result.joinToString(prefix = "AccessToLogicMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_id: String = this.user_id,
    session_id: String = this.session_id,
    gateway_id: String = this.gateway_id,
    device_id: String = this.device_id,
    platform: Platform = this.platform,
    user_message: UserMessage? = this.user_message,
    ack: MsgAck? = this.ack,
    system_cmd: SystemCommand? = this.system_cmd,
    unknownFields: ByteString = this.unknownFields,
  ): AccessToLogicMsg = AccessToLogicMsg(user_id, session_id, gateway_id, device_id, platform, user_message, ack, system_cmd, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AccessToLogicMsg> = object : ProtoAdapter<AccessToLogicMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      AccessToLogicMsg::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.AccessToLogicMsg", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: AccessToLogicMsg): Int {
        var size = value.unknownFields.size
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id)
        }
        if (value.session_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.session_id)
        }
        if (value.gateway_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.gateway_id)
        }
        if (value.device_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.device_id)
        }
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          size += Platform.ADAPTER.encodedSizeWithTag(5, value.platform)
        }
        size += UserMessage.ADAPTER.encodedSizeWithTag(10, value.user_message)
        size += MsgAck.ADAPTER.encodedSizeWithTag(11, value.ack)
        size += SystemCommand.ADAPTER.encodedSizeWithTag(12, value.system_cmd)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AccessToLogicMsg) {
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.session_id)
        }
        if (value.gateway_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.gateway_id)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.device_id)
        }
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          Platform.ADAPTER.encodeWithTag(writer, 5, value.platform)
        }
        UserMessage.ADAPTER.encodeWithTag(writer, 10, value.user_message)
        MsgAck.ADAPTER.encodeWithTag(writer, 11, value.ack)
        SystemCommand.ADAPTER.encodeWithTag(writer, 12, value.system_cmd)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AccessToLogicMsg) {
        writer.writeBytes(value.unknownFields)
        SystemCommand.ADAPTER.encodeWithTag(writer, 12, value.system_cmd)
        MsgAck.ADAPTER.encodeWithTag(writer, 11, value.ack)
        UserMessage.ADAPTER.encodeWithTag(writer, 10, value.user_message)
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          Platform.ADAPTER.encodeWithTag(writer, 5, value.platform)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.device_id)
        }
        if (value.gateway_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.gateway_id)
        }
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.session_id)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
      }

      override fun decode(reader: ProtoReader): AccessToLogicMsg {
        var user_id: String = ""
        var session_id: String = ""
        var gateway_id: String = ""
        var device_id: String = ""
        var platform: Platform = Platform.PLATFORM_UNKNOWN
        var user_message: UserMessage? = null
        var ack: MsgAck? = null
        var system_cmd: SystemCommand? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_id = ProtoAdapter.STRING.decode(reader)
            2 -> session_id = ProtoAdapter.STRING.decode(reader)
            3 -> gateway_id = ProtoAdapter.STRING.decode(reader)
            4 -> device_id = ProtoAdapter.STRING.decode(reader)
            5 -> try {
              platform = Platform.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            10 -> user_message = UserMessage.ADAPTER.decode(reader)
            11 -> ack = MsgAck.ADAPTER.decode(reader)
            12 -> system_cmd = SystemCommand.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AccessToLogicMsg(
          user_id = user_id,
          session_id = session_id,
          gateway_id = gateway_id,
          device_id = device_id,
          platform = platform,
          user_message = user_message,
          ack = ack,
          system_cmd = system_cmd,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AccessToLogicMsg): AccessToLogicMsg = value.copy(
        user_message = value.user_message?.let(UserMessage.ADAPTER::redact),
        ack = value.ack?.let(MsgAck.ADAPTER::redact),
        system_cmd = value.system_cmd?.let(SystemCommand.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
