// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.AuthResp in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * --- Responses ---
 */
public class AuthResp(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.UserInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val user: UserInfo? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sessionId",
    schemaIndex = 1,
  )
  public val session_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AuthResp, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AuthResp) return false
    if (unknownFields != other.unknownFields) return false
    if (user != other.user) return false
    if (session_id != other.session_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (user?.hashCode() ?: 0)
      result = result * 37 + session_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (user != null) result += """user=$user"""
    result += """session_id=${sanitize(session_id)}"""
    return result.joinToString(prefix = "AuthResp{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user: UserInfo? = this.user,
    session_id: String = this.session_id,
    unknownFields: ByteString = this.unknownFields,
  ): AuthResp = AuthResp(user, session_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AuthResp> = object : ProtoAdapter<AuthResp>(
      FieldEncoding.LENGTH_DELIMITED, 
      AuthResp::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.AuthResp", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: AuthResp): Int {
        var size = value.unknownFields.size
        if (value.user != null) {
          size += UserInfo.ADAPTER.encodedSizeWithTag(1, value.user)
        }
        if (value.session_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.session_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AuthResp) {
        if (value.user != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 1, value.user)
        }
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.session_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AuthResp) {
        writer.writeBytes(value.unknownFields)
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.session_id)
        }
        if (value.user != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 1, value.user)
        }
      }

      override fun decode(reader: ProtoReader): AuthResp {
        var user: UserInfo? = null
        var session_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user = UserInfo.ADAPTER.decode(reader)
            2 -> session_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AuthResp(
          user = user,
          session_id = session_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AuthResp): AuthResp = value.copy(
        user = value.user?.let(UserInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
