// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.BroadcastCommand in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * 广播指令
 */
public class BroadcastCommand(
  user_ids: List<String> = emptyList(),
  /**
   * 房间ID (房间广播)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 1,
  )
  public val room_id: String = "",
  /**
   * 广播的消息内容
   */
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.UserMessagePush#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val message: UserMessagePush? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<BroadcastCommand, Nothing>(ADAPTER, unknownFields) {
  /**
   * 目标用户列表，为空表示全体用户
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "userIds",
    schemaIndex = 0,
  )
  public val user_ids: List<String> = immutableCopyOf("user_ids", user_ids)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BroadcastCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (user_ids != other.user_ids) return false
    if (room_id != other.room_id) return false
    if (message != other.message) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_ids.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + (message?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (user_ids.isNotEmpty()) result += """user_ids=${sanitize(user_ids)}"""
    result += """room_id=${sanitize(room_id)}"""
    if (message != null) result += """message=$message"""
    return result.joinToString(prefix = "BroadcastCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_ids: List<String> = this.user_ids,
    room_id: String = this.room_id,
    message: UserMessagePush? = this.message,
    unknownFields: ByteString = this.unknownFields,
  ): BroadcastCommand = BroadcastCommand(user_ids, room_id, message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BroadcastCommand> = object : ProtoAdapter<BroadcastCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      BroadcastCommand::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.BroadcastCommand", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: BroadcastCommand): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.user_ids)
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.room_id)
        }
        if (value.message != null) {
          size += UserMessagePush.ADAPTER.encodedSizeWithTag(3, value.message)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BroadcastCommand) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.user_ids)
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.room_id)
        }
        if (value.message != null) {
          UserMessagePush.ADAPTER.encodeWithTag(writer, 3, value.message)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BroadcastCommand) {
        writer.writeBytes(value.unknownFields)
        if (value.message != null) {
          UserMessagePush.ADAPTER.encodeWithTag(writer, 3, value.message)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.room_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.user_ids)
      }

      override fun decode(reader: ProtoReader): BroadcastCommand {
        val user_ids = mutableListOf<String>()
        var room_id: String = ""
        var message: UserMessagePush? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_ids.add(ProtoAdapter.STRING.decode(reader))
            2 -> room_id = ProtoAdapter.STRING.decode(reader)
            3 -> message = UserMessagePush.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BroadcastCommand(
          user_ids = user_ids,
          room_id = room_id,
          message = message,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BroadcastCommand): BroadcastCommand = value.copy(
        message = value.message?.let(UserMessagePush.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
