// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ChatSendAck in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ChatSendAck(
  /**
   * 服务端生成的消息ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgId",
    schemaIndex = 0,
  )
  public val msg_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sendTime",
    schemaIndex = 1,
  )
  public val send_time: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatSendAck, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatSendAck) return false
    if (unknownFields != other.unknownFields) return false
    if (msg_id != other.msg_id) return false
    if (send_time != other.send_time) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + msg_id.hashCode()
      result = result * 37 + send_time.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """msg_id=${sanitize(msg_id)}"""
    result += """send_time=$send_time"""
    return result.joinToString(prefix = "ChatSendAck{", separator = ", ", postfix = "}")
  }

  public fun copy(
    msg_id: String = this.msg_id,
    send_time: Long = this.send_time,
    unknownFields: ByteString = this.unknownFields,
  ): ChatSendAck = ChatSendAck(msg_id, send_time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatSendAck> = object : ProtoAdapter<ChatSendAck>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatSendAck::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ChatSendAck", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: ChatSendAck): Int {
        var size = value.unknownFields.size
        if (value.msg_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.msg_id)
        }
        if (value.send_time != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.send_time)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatSendAck) {
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
        if (value.send_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.send_time)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatSendAck) {
        writer.writeBytes(value.unknownFields)
        if (value.send_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.send_time)
        }
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
      }

      override fun decode(reader: ProtoReader): ChatSendAck {
        var msg_id: String = ""
        var send_time: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> msg_id = ProtoAdapter.STRING.decode(reader)
            2 -> send_time = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatSendAck(
          msg_id = msg_id,
          send_time = send_time,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatSendAck): ChatSendAck = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
