// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ChatType in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class ChatType(
  override val `value`: Int,
) : WireEnum {
  CHAT_TYPE_UNKNOWN(0),
  /**
   * 私聊
   */
  CHAT_PRIVATE(1),
  /**
   * 群聊
   */
  CHAT_GROUP(2),
  /**
   * 系统通知
   */
  CHAT_SYSTEM(3),
  /**
   * 麻将指令
   */
  CHAT_MAHJONG(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatType> = object : EnumAdapter<ChatType>(
      ChatType::class, 
      PROTO_3, 
      ChatType.CHAT_TYPE_UNKNOWN
    ) {
      override fun fromValue(`value`: Int): ChatType? = ChatType.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ChatType? = when (`value`) {
      0 -> CHAT_TYPE_UNKNOWN
      1 -> CHAT_PRIVATE
      2 -> CHAT_GROUP
      3 -> CHAT_SYSTEM
      4 -> CHAT_MAHJONG
      else -> null
    }
  }
}
