// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ChatPush in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * --- Pushes ---
 */
public class ChatPush(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgId",
    schemaIndex = 0,
  )
  public val msg_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "senderId",
    schemaIndex = 1,
  )
  public val sender_id: String = "",
  /**
   * 发送者信息快照
   */
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.UserInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "senderInfo",
    schemaIndex = 2,
  )
  public val sender_info: UserInfo? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.sudooom.mahjong.common.proto.ChatType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "chatType",
    schemaIndex = 3,
  )
  public val chat_type: ChatType = ChatType.CHAT_TYPE_UNKNOWN,
  /**
   * 群ID 或 自己的ID
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "targetId",
    schemaIndex = 4,
  )
  public val target_id: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.sudooom.mahjong.common.proto.MsgType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgType",
    schemaIndex = 5,
  )
  public val msg_type: MsgType = MsgType.MSG_TYPE_UNKNOWN,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val content: String = "",
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sendTime",
    schemaIndex = 7,
  )
  public val send_time: Long = 0L,
  ext: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatPush, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 9,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 8,
  )
  public val ext: Map<String, String> = immutableCopyOf("ext", ext)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatPush) return false
    if (unknownFields != other.unknownFields) return false
    if (msg_id != other.msg_id) return false
    if (sender_id != other.sender_id) return false
    if (sender_info != other.sender_info) return false
    if (chat_type != other.chat_type) return false
    if (target_id != other.target_id) return false
    if (msg_type != other.msg_type) return false
    if (content != other.content) return false
    if (send_time != other.send_time) return false
    if (ext != other.ext) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + msg_id.hashCode()
      result = result * 37 + sender_id.hashCode()
      result = result * 37 + (sender_info?.hashCode() ?: 0)
      result = result * 37 + chat_type.hashCode()
      result = result * 37 + target_id.hashCode()
      result = result * 37 + msg_type.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + send_time.hashCode()
      result = result * 37 + ext.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """msg_id=${sanitize(msg_id)}"""
    result += """sender_id=${sanitize(sender_id)}"""
    if (sender_info != null) result += """sender_info=$sender_info"""
    result += """chat_type=$chat_type"""
    result += """target_id=${sanitize(target_id)}"""
    result += """msg_type=$msg_type"""
    result += """content=${sanitize(content)}"""
    result += """send_time=$send_time"""
    if (ext.isNotEmpty()) result += """ext=$ext"""
    return result.joinToString(prefix = "ChatPush{", separator = ", ", postfix = "}")
  }

  public fun copy(
    msg_id: String = this.msg_id,
    sender_id: String = this.sender_id,
    sender_info: UserInfo? = this.sender_info,
    chat_type: ChatType = this.chat_type,
    target_id: String = this.target_id,
    msg_type: MsgType = this.msg_type,
    content: String = this.content,
    send_time: Long = this.send_time,
    ext: Map<String, String> = this.ext,
    unknownFields: ByteString = this.unknownFields,
  ): ChatPush = ChatPush(msg_id, sender_id, sender_info, chat_type, target_id, msg_type, content, send_time, ext, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatPush> = object : ProtoAdapter<ChatPush>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatPush::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ChatPush", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      private val extAdapter: ProtoAdapter<Map<String, String>> by
          lazy { ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: ChatPush): Int {
        var size = value.unknownFields.size
        if (value.msg_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.msg_id)
        }
        if (value.sender_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.sender_id)
        }
        if (value.sender_info != null) {
          size += UserInfo.ADAPTER.encodedSizeWithTag(3, value.sender_info)
        }
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          size += ChatType.ADAPTER.encodedSizeWithTag(4, value.chat_type)
        }
        if (value.target_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.target_id)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          size += MsgType.ADAPTER.encodedSizeWithTag(6, value.msg_type)
        }
        if (value.content != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.content)
        }
        if (value.send_time != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(8, value.send_time)
        }
        size += extAdapter.encodedSizeWithTag(9, value.ext)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatPush) {
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
        if (value.sender_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.sender_id)
        }
        if (value.sender_info != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 3, value.sender_info)
        }
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          ChatType.ADAPTER.encodeWithTag(writer, 4, value.chat_type)
        }
        if (value.target_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.target_id)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          MsgType.ADAPTER.encodeWithTag(writer, 6, value.msg_type)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.content)
        }
        if (value.send_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 8, value.send_time)
        }
        extAdapter.encodeWithTag(writer, 9, value.ext)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatPush) {
        writer.writeBytes(value.unknownFields)
        extAdapter.encodeWithTag(writer, 9, value.ext)
        if (value.send_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 8, value.send_time)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.content)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          MsgType.ADAPTER.encodeWithTag(writer, 6, value.msg_type)
        }
        if (value.target_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.target_id)
        }
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          ChatType.ADAPTER.encodeWithTag(writer, 4, value.chat_type)
        }
        if (value.sender_info != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 3, value.sender_info)
        }
        if (value.sender_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.sender_id)
        }
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
      }

      override fun decode(reader: ProtoReader): ChatPush {
        var msg_id: String = ""
        var sender_id: String = ""
        var sender_info: UserInfo? = null
        var chat_type: ChatType = ChatType.CHAT_TYPE_UNKNOWN
        var target_id: String = ""
        var msg_type: MsgType = MsgType.MSG_TYPE_UNKNOWN
        var content: String = ""
        var send_time: Long = 0L
        val ext = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> msg_id = ProtoAdapter.STRING.decode(reader)
            2 -> sender_id = ProtoAdapter.STRING.decode(reader)
            3 -> sender_info = UserInfo.ADAPTER.decode(reader)
            4 -> try {
              chat_type = ChatType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            5 -> target_id = ProtoAdapter.STRING.decode(reader)
            6 -> try {
              msg_type = MsgType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            7 -> content = ProtoAdapter.STRING.decode(reader)
            8 -> send_time = ProtoAdapter.INT64.decode(reader)
            9 -> ext.putAll(extAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatPush(
          msg_id = msg_id,
          sender_id = sender_id,
          sender_info = sender_info,
          chat_type = chat_type,
          target_id = target_id,
          msg_type = msg_type,
          content = content,
          send_time = send_time,
          ext = ext,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatPush): ChatPush = value.copy(
        sender_info = value.sender_info?.let(UserInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
