// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ChatSendReq in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

public class ChatSendReq(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.ChatType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "chatType",
    schemaIndex = 0,
  )
  public val chat_type: ChatType = ChatType.CHAT_TYPE_UNKNOWN,
  /**
   * 接收者ID 或 群ID
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "targetId",
    schemaIndex = 1,
  )
  public val target_id: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.MsgType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgType",
    schemaIndex = 2,
  )
  public val msg_type: MsgType = MsgType.MSG_TYPE_UNKNOWN,
  /**
   * 消息内容 (JSON string for complex types)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val content: String = "",
  ext: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatSendReq, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 5,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 4,
  )
  public val ext: Map<String, String> = immutableCopyOf("ext", ext)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatSendReq) return false
    if (unknownFields != other.unknownFields) return false
    if (chat_type != other.chat_type) return false
    if (target_id != other.target_id) return false
    if (msg_type != other.msg_type) return false
    if (content != other.content) return false
    if (ext != other.ext) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + chat_type.hashCode()
      result = result * 37 + target_id.hashCode()
      result = result * 37 + msg_type.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + ext.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """chat_type=$chat_type"""
    result += """target_id=${sanitize(target_id)}"""
    result += """msg_type=$msg_type"""
    result += """content=${sanitize(content)}"""
    if (ext.isNotEmpty()) result += """ext=$ext"""
    return result.joinToString(prefix = "ChatSendReq{", separator = ", ", postfix = "}")
  }

  public fun copy(
    chat_type: ChatType = this.chat_type,
    target_id: String = this.target_id,
    msg_type: MsgType = this.msg_type,
    content: String = this.content,
    ext: Map<String, String> = this.ext,
    unknownFields: ByteString = this.unknownFields,
  ): ChatSendReq = ChatSendReq(chat_type, target_id, msg_type, content, ext, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatSendReq> = object : ProtoAdapter<ChatSendReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatSendReq::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ChatSendReq", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      private val extAdapter: ProtoAdapter<Map<String, String>> by
          lazy { ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: ChatSendReq): Int {
        var size = value.unknownFields.size
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          size += ChatType.ADAPTER.encodedSizeWithTag(1, value.chat_type)
        }
        if (value.target_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.target_id)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          size += MsgType.ADAPTER.encodedSizeWithTag(3, value.msg_type)
        }
        if (value.content != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.content)
        }
        size += extAdapter.encodedSizeWithTag(5, value.ext)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatSendReq) {
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          ChatType.ADAPTER.encodeWithTag(writer, 1, value.chat_type)
        }
        if (value.target_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.target_id)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          MsgType.ADAPTER.encodeWithTag(writer, 3, value.msg_type)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content)
        }
        extAdapter.encodeWithTag(writer, 5, value.ext)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatSendReq) {
        writer.writeBytes(value.unknownFields)
        extAdapter.encodeWithTag(writer, 5, value.ext)
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.content)
        }
        if (value.msg_type != com.sudooom.mahjong.common.proto.MsgType.MSG_TYPE_UNKNOWN) {
          MsgType.ADAPTER.encodeWithTag(writer, 3, value.msg_type)
        }
        if (value.target_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.target_id)
        }
        if (value.chat_type != com.sudooom.mahjong.common.proto.ChatType.CHAT_TYPE_UNKNOWN) {
          ChatType.ADAPTER.encodeWithTag(writer, 1, value.chat_type)
        }
      }

      override fun decode(reader: ProtoReader): ChatSendReq {
        var chat_type: ChatType = ChatType.CHAT_TYPE_UNKNOWN
        var target_id: String = ""
        var msg_type: MsgType = MsgType.MSG_TYPE_UNKNOWN
        var content: String = ""
        val ext = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              chat_type = ChatType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> target_id = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              msg_type = MsgType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> content = ProtoAdapter.STRING.decode(reader)
            5 -> ext.putAll(extAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatSendReq(
          chat_type = chat_type,
          target_id = target_id,
          msg_type = msg_type,
          content = content,
          ext = ext,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatSendReq): ChatSendReq = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
