// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ClientRequest in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * Client Request (Client -> Server)
 * =============================================================================
 */
public class ClientRequest(
  /**
   * 请求ID，用于匹配响应
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "reqId",
    schemaIndex = 0,
  )
  public val req_id: String = "",
  /**
   * 请求时间戳
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val timestamp: Long = 0L,
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.ChatSendReq#ADAPTER",
    jsonName = "chatSend",
    oneofName = "payload",
    schemaIndex = 2,
  )
  public val chat_send: ChatSendReq? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.GameReq#ADAPTER",
    oneofName = "payload",
    schemaIndex = 3,
  )
  public val game: GameReq? = null,
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.HeartbeatReq#ADAPTER",
    oneofName = "payload",
    schemaIndex = 4,
  )
  public val heartbeat: HeartbeatReq? = null,
  @field:WireField(
    tag = 14,
    adapter = "com.sudooom.mahjong.common.proto.RoomReq#ADAPTER",
    oneofName = "payload",
    schemaIndex = 5,
  )
  public val room: RoomReq? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ClientRequest, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(chat_send, game, heartbeat, room) <= 1) {
      "At most one of chat_send, game, heartbeat, room may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ClientRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (req_id != other.req_id) return false
    if (timestamp != other.timestamp) return false
    if (chat_send != other.chat_send) return false
    if (game != other.game) return false
    if (heartbeat != other.heartbeat) return false
    if (room != other.room) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + req_id.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + (chat_send?.hashCode() ?: 0)
      result = result * 37 + (game?.hashCode() ?: 0)
      result = result * 37 + (heartbeat?.hashCode() ?: 0)
      result = result * 37 + (room?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """req_id=${sanitize(req_id)}"""
    result += """timestamp=$timestamp"""
    if (chat_send != null) result += """chat_send=$chat_send"""
    if (game != null) result += """game=$game"""
    if (heartbeat != null) result += """heartbeat=$heartbeat"""
    if (room != null) result += """room=$room"""
    return result.joinToString(prefix = "ClientRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    req_id: String = this.req_id,
    timestamp: Long = this.timestamp,
    chat_send: ChatSendReq? = this.chat_send,
    game: GameReq? = this.game,
    heartbeat: HeartbeatReq? = this.heartbeat,
    room: RoomReq? = this.room,
    unknownFields: ByteString = this.unknownFields,
  ): ClientRequest = ClientRequest(req_id, timestamp, chat_send, game, heartbeat, room, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ClientRequest> = object : ProtoAdapter<ClientRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ClientRequest::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ClientRequest", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: ClientRequest): Int {
        var size = value.unknownFields.size
        if (value.req_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.req_id)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.timestamp)
        }
        size += ChatSendReq.ADAPTER.encodedSizeWithTag(11, value.chat_send)
        size += GameReq.ADAPTER.encodedSizeWithTag(12, value.game)
        size += HeartbeatReq.ADAPTER.encodedSizeWithTag(13, value.heartbeat)
        size += RoomReq.ADAPTER.encodedSizeWithTag(14, value.room)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ClientRequest) {
        if (value.req_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.req_id)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.timestamp)
        }
        ChatSendReq.ADAPTER.encodeWithTag(writer, 11, value.chat_send)
        GameReq.ADAPTER.encodeWithTag(writer, 12, value.game)
        HeartbeatReq.ADAPTER.encodeWithTag(writer, 13, value.heartbeat)
        RoomReq.ADAPTER.encodeWithTag(writer, 14, value.room)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ClientRequest) {
        writer.writeBytes(value.unknownFields)
        RoomReq.ADAPTER.encodeWithTag(writer, 14, value.room)
        HeartbeatReq.ADAPTER.encodeWithTag(writer, 13, value.heartbeat)
        GameReq.ADAPTER.encodeWithTag(writer, 12, value.game)
        ChatSendReq.ADAPTER.encodeWithTag(writer, 11, value.chat_send)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.timestamp)
        }
        if (value.req_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.req_id)
        }
      }

      override fun decode(reader: ProtoReader): ClientRequest {
        var req_id: String = ""
        var timestamp: Long = 0L
        var chat_send: ChatSendReq? = null
        var game: GameReq? = null
        var heartbeat: HeartbeatReq? = null
        var room: RoomReq? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> req_id = ProtoAdapter.STRING.decode(reader)
            2 -> timestamp = ProtoAdapter.INT64.decode(reader)
            11 -> chat_send = ChatSendReq.ADAPTER.decode(reader)
            12 -> game = GameReq.ADAPTER.decode(reader)
            13 -> heartbeat = HeartbeatReq.ADAPTER.decode(reader)
            14 -> room = RoomReq.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ClientRequest(
          req_id = req_id,
          timestamp = timestamp,
          chat_send = chat_send,
          game = game,
          heartbeat = heartbeat,
          room = room,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ClientRequest): ClientRequest = value.copy(
        chat_send = value.chat_send?.let(ChatSendReq.ADAPTER::redact),
        game = value.game?.let(GameReq.ADAPTER::redact),
        heartbeat = value.heartbeat?.let(HeartbeatReq.ADAPTER::redact),
        room = value.room?.let(RoomReq.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
