// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ClientResponse in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * Client Response (Server -> Client)
 * Includes both Responses (to requests) and Pushes (server events)
 * =============================================================================
 */
public class ClientResponse(
  /**
   * 如果是响应，对应请求ID；如果是推送，可能为空或特定ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "reqId",
    schemaIndex = 0,
  )
  public val req_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val timestamp: Long = 0L,
  /**
   * 状态码
   */
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.ErrorCode#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val code: ErrorCode = ErrorCode.SUCCESS,
  /**
   * 错误信息或提示
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val msg: String = "",
  /**
   * Responses
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.AuthResp#ADAPTER",
    jsonName = "authResp",
    oneofName = "payload",
    schemaIndex = 4,
  )
  public val auth_resp: AuthResp? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.ChatSendAck#ADAPTER",
    jsonName = "chatSendAck",
    oneofName = "payload",
    schemaIndex = 5,
  )
  public val chat_send_ack: ChatSendAck? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.RoomResp#ADAPTER",
    jsonName = "roomResp",
    oneofName = "payload",
    schemaIndex = 6,
  )
  public val room_resp: RoomResp? = null,
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.HeartbeatResp#ADAPTER",
    jsonName = "heartbeatResp",
    oneofName = "payload",
    schemaIndex = 7,
  )
  public val heartbeat_resp: HeartbeatResp? = null,
  /**
   * Pushes
   */
  @field:WireField(
    tag = 20,
    adapter = "com.sudooom.mahjong.common.proto.ChatPush#ADAPTER",
    jsonName = "chatPush",
    oneofName = "payload",
    schemaIndex = 8,
  )
  public val chat_push: ChatPush? = null,
  @field:WireField(
    tag = 21,
    adapter = "com.sudooom.mahjong.common.proto.GamePush#ADAPTER",
    jsonName = "gamePush",
    oneofName = "payload",
    schemaIndex = 9,
  )
  public val game_push: GamePush? = null,
  @field:WireField(
    tag = 22,
    adapter = "com.sudooom.mahjong.common.proto.RoomPush#ADAPTER",
    jsonName = "roomPush",
    oneofName = "payload",
    schemaIndex = 10,
  )
  public val room_push: RoomPush? = null,
  @field:WireField(
    tag = 23,
    adapter = "com.sudooom.mahjong.common.proto.SystemPush#ADAPTER",
    jsonName = "systemPush",
    oneofName = "payload",
    schemaIndex = 11,
  )
  public val system_push: SystemPush? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ClientResponse, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(auth_resp, chat_send_ack, room_resp, heartbeat_resp, chat_push, game_push, room_push, system_push) <= 1) {
      "At most one of auth_resp, chat_send_ack, room_resp, heartbeat_resp, chat_push, game_push, room_push, system_push may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ClientResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (req_id != other.req_id) return false
    if (timestamp != other.timestamp) return false
    if (code != other.code) return false
    if (msg != other.msg) return false
    if (auth_resp != other.auth_resp) return false
    if (chat_send_ack != other.chat_send_ack) return false
    if (room_resp != other.room_resp) return false
    if (heartbeat_resp != other.heartbeat_resp) return false
    if (chat_push != other.chat_push) return false
    if (game_push != other.game_push) return false
    if (room_push != other.room_push) return false
    if (system_push != other.system_push) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + req_id.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + code.hashCode()
      result = result * 37 + msg.hashCode()
      result = result * 37 + (auth_resp?.hashCode() ?: 0)
      result = result * 37 + (chat_send_ack?.hashCode() ?: 0)
      result = result * 37 + (room_resp?.hashCode() ?: 0)
      result = result * 37 + (heartbeat_resp?.hashCode() ?: 0)
      result = result * 37 + (chat_push?.hashCode() ?: 0)
      result = result * 37 + (game_push?.hashCode() ?: 0)
      result = result * 37 + (room_push?.hashCode() ?: 0)
      result = result * 37 + (system_push?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """req_id=${sanitize(req_id)}"""
    result += """timestamp=$timestamp"""
    result += """code=$code"""
    result += """msg=${sanitize(msg)}"""
    if (auth_resp != null) result += """auth_resp=$auth_resp"""
    if (chat_send_ack != null) result += """chat_send_ack=$chat_send_ack"""
    if (room_resp != null) result += """room_resp=$room_resp"""
    if (heartbeat_resp != null) result += """heartbeat_resp=$heartbeat_resp"""
    if (chat_push != null) result += """chat_push=$chat_push"""
    if (game_push != null) result += """game_push=$game_push"""
    if (room_push != null) result += """room_push=$room_push"""
    if (system_push != null) result += """system_push=$system_push"""
    return result.joinToString(prefix = "ClientResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    req_id: String = this.req_id,
    timestamp: Long = this.timestamp,
    code: ErrorCode = this.code,
    msg: String = this.msg,
    auth_resp: AuthResp? = this.auth_resp,
    chat_send_ack: ChatSendAck? = this.chat_send_ack,
    room_resp: RoomResp? = this.room_resp,
    heartbeat_resp: HeartbeatResp? = this.heartbeat_resp,
    chat_push: ChatPush? = this.chat_push,
    game_push: GamePush? = this.game_push,
    room_push: RoomPush? = this.room_push,
    system_push: SystemPush? = this.system_push,
    unknownFields: ByteString = this.unknownFields,
  ): ClientResponse = ClientResponse(req_id, timestamp, code, msg, auth_resp, chat_send_ack, room_resp, heartbeat_resp, chat_push, game_push, room_push, system_push, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ClientResponse> = object : ProtoAdapter<ClientResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ClientResponse::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ClientResponse", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: ClientResponse): Int {
        var size = value.unknownFields.size
        if (value.req_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.req_id)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.timestamp)
        }
        if (value.code != com.sudooom.mahjong.common.proto.ErrorCode.SUCCESS) {
          size += ErrorCode.ADAPTER.encodedSizeWithTag(3, value.code)
        }
        if (value.msg != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.msg)
        }
        size += AuthResp.ADAPTER.encodedSizeWithTag(10, value.auth_resp)
        size += ChatSendAck.ADAPTER.encodedSizeWithTag(11, value.chat_send_ack)
        size += RoomResp.ADAPTER.encodedSizeWithTag(12, value.room_resp)
        size += HeartbeatResp.ADAPTER.encodedSizeWithTag(13, value.heartbeat_resp)
        size += ChatPush.ADAPTER.encodedSizeWithTag(20, value.chat_push)
        size += GamePush.ADAPTER.encodedSizeWithTag(21, value.game_push)
        size += RoomPush.ADAPTER.encodedSizeWithTag(22, value.room_push)
        size += SystemPush.ADAPTER.encodedSizeWithTag(23, value.system_push)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ClientResponse) {
        if (value.req_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.req_id)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.timestamp)
        }
        if (value.code != com.sudooom.mahjong.common.proto.ErrorCode.SUCCESS) {
          ErrorCode.ADAPTER.encodeWithTag(writer, 3, value.code)
        }
        if (value.msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.msg)
        }
        AuthResp.ADAPTER.encodeWithTag(writer, 10, value.auth_resp)
        ChatSendAck.ADAPTER.encodeWithTag(writer, 11, value.chat_send_ack)
        RoomResp.ADAPTER.encodeWithTag(writer, 12, value.room_resp)
        HeartbeatResp.ADAPTER.encodeWithTag(writer, 13, value.heartbeat_resp)
        ChatPush.ADAPTER.encodeWithTag(writer, 20, value.chat_push)
        GamePush.ADAPTER.encodeWithTag(writer, 21, value.game_push)
        RoomPush.ADAPTER.encodeWithTag(writer, 22, value.room_push)
        SystemPush.ADAPTER.encodeWithTag(writer, 23, value.system_push)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ClientResponse) {
        writer.writeBytes(value.unknownFields)
        SystemPush.ADAPTER.encodeWithTag(writer, 23, value.system_push)
        RoomPush.ADAPTER.encodeWithTag(writer, 22, value.room_push)
        GamePush.ADAPTER.encodeWithTag(writer, 21, value.game_push)
        ChatPush.ADAPTER.encodeWithTag(writer, 20, value.chat_push)
        HeartbeatResp.ADAPTER.encodeWithTag(writer, 13, value.heartbeat_resp)
        RoomResp.ADAPTER.encodeWithTag(writer, 12, value.room_resp)
        ChatSendAck.ADAPTER.encodeWithTag(writer, 11, value.chat_send_ack)
        AuthResp.ADAPTER.encodeWithTag(writer, 10, value.auth_resp)
        if (value.msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.msg)
        }
        if (value.code != com.sudooom.mahjong.common.proto.ErrorCode.SUCCESS) {
          ErrorCode.ADAPTER.encodeWithTag(writer, 3, value.code)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.timestamp)
        }
        if (value.req_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.req_id)
        }
      }

      override fun decode(reader: ProtoReader): ClientResponse {
        var req_id: String = ""
        var timestamp: Long = 0L
        var code: ErrorCode = ErrorCode.SUCCESS
        var msg: String = ""
        var auth_resp: AuthResp? = null
        var chat_send_ack: ChatSendAck? = null
        var room_resp: RoomResp? = null
        var heartbeat_resp: HeartbeatResp? = null
        var chat_push: ChatPush? = null
        var game_push: GamePush? = null
        var room_push: RoomPush? = null
        var system_push: SystemPush? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> req_id = ProtoAdapter.STRING.decode(reader)
            2 -> timestamp = ProtoAdapter.INT64.decode(reader)
            3 -> try {
              code = ErrorCode.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> msg = ProtoAdapter.STRING.decode(reader)
            10 -> auth_resp = AuthResp.ADAPTER.decode(reader)
            11 -> chat_send_ack = ChatSendAck.ADAPTER.decode(reader)
            12 -> room_resp = RoomResp.ADAPTER.decode(reader)
            13 -> heartbeat_resp = HeartbeatResp.ADAPTER.decode(reader)
            20 -> chat_push = ChatPush.ADAPTER.decode(reader)
            21 -> game_push = GamePush.ADAPTER.decode(reader)
            22 -> room_push = RoomPush.ADAPTER.decode(reader)
            23 -> system_push = SystemPush.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ClientResponse(
          req_id = req_id,
          timestamp = timestamp,
          code = code,
          msg = msg,
          auth_resp = auth_resp,
          chat_send_ack = chat_send_ack,
          room_resp = room_resp,
          heartbeat_resp = heartbeat_resp,
          chat_push = chat_push,
          game_push = game_push,
          room_push = room_push,
          system_push = system_push,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ClientResponse): ClientResponse = value.copy(
        auth_resp = value.auth_resp?.let(AuthResp.ADAPTER::redact),
        chat_send_ack = value.chat_send_ack?.let(ChatSendAck.ADAPTER::redact),
        room_resp = value.room_resp?.let(RoomResp.ADAPTER::redact),
        heartbeat_resp = value.heartbeat_resp?.let(HeartbeatResp.ADAPTER::redact),
        chat_push = value.chat_push?.let(ChatPush.ADAPTER::redact),
        game_push = value.game_push?.let(GamePush.ADAPTER::redact),
        room_push = value.room_push?.let(RoomPush.ADAPTER::redact),
        system_push = value.system_push?.let(SystemPush.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
