// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.CompensationCommand in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * 补偿指令
 */
public class CompensationCommand(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "compensationId",
    schemaIndex = 0,
  )
  public val compensation_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "originalTraceId",
    schemaIndex = 1,
  )
  public val original_trace_id: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.CompensationCommand${'$'}CompensationType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val type: CompensationType = CompensationType.RETRY,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "errorCode",
    schemaIndex = 3,
  )
  public val error_code: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "errorMsg",
    schemaIndex = 4,
  )
  public val error_msg: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "retryCount",
    schemaIndex = 5,
  )
  public val retry_count: Int = 0,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "maxRetry",
    schemaIndex = 6,
  )
  public val max_retry: Int = 0,
  /**
   * 原始消息数据 (用于重试)
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "originalPayload",
    schemaIndex = 7,
  )
  public val original_payload: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CompensationCommand, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CompensationCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (compensation_id != other.compensation_id) return false
    if (original_trace_id != other.original_trace_id) return false
    if (type != other.type) return false
    if (error_code != other.error_code) return false
    if (error_msg != other.error_msg) return false
    if (retry_count != other.retry_count) return false
    if (max_retry != other.max_retry) return false
    if (original_payload != other.original_payload) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + compensation_id.hashCode()
      result = result * 37 + original_trace_id.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + error_code.hashCode()
      result = result * 37 + error_msg.hashCode()
      result = result * 37 + retry_count.hashCode()
      result = result * 37 + max_retry.hashCode()
      result = result * 37 + original_payload.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """compensation_id=${sanitize(compensation_id)}"""
    result += """original_trace_id=${sanitize(original_trace_id)}"""
    result += """type=$type"""
    result += """error_code=${sanitize(error_code)}"""
    result += """error_msg=${sanitize(error_msg)}"""
    result += """retry_count=$retry_count"""
    result += """max_retry=$max_retry"""
    result += """original_payload=$original_payload"""
    return result.joinToString(prefix = "CompensationCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(
    compensation_id: String = this.compensation_id,
    original_trace_id: String = this.original_trace_id,
    type: CompensationType = this.type,
    error_code: String = this.error_code,
    error_msg: String = this.error_msg,
    retry_count: Int = this.retry_count,
    max_retry: Int = this.max_retry,
    original_payload: ByteString = this.original_payload,
    unknownFields: ByteString = this.unknownFields,
  ): CompensationCommand = CompensationCommand(compensation_id, original_trace_id, type, error_code, error_msg, retry_count, max_retry, original_payload, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CompensationCommand> =
        object : ProtoAdapter<CompensationCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      CompensationCommand::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.CompensationCommand", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: CompensationCommand): Int {
        var size = value.unknownFields.size
        if (value.compensation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.compensation_id)
        }
        if (value.original_trace_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.original_trace_id)
        }
        if (value.type != com.sudooom.mahjong.common.proto.CompensationCommand.CompensationType.RETRY) {
          size += CompensationType.ADAPTER.encodedSizeWithTag(3, value.type)
        }
        if (value.error_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.error_code)
        }
        if (value.error_msg != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.error_msg)
        }
        if (value.retry_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.retry_count)
        }
        if (value.max_retry != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(7, value.max_retry)
        }
        if (value.original_payload != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(10, value.original_payload)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CompensationCommand) {
        if (value.compensation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.compensation_id)
        }
        if (value.original_trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.original_trace_id)
        }
        if (value.type != com.sudooom.mahjong.common.proto.CompensationCommand.CompensationType.RETRY) {
          CompensationType.ADAPTER.encodeWithTag(writer, 3, value.type)
        }
        if (value.error_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.error_code)
        }
        if (value.error_msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.error_msg)
        }
        if (value.retry_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.retry_count)
        }
        if (value.max_retry != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 7, value.max_retry)
        }
        if (value.original_payload != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 10, value.original_payload)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CompensationCommand) {
        writer.writeBytes(value.unknownFields)
        if (value.original_payload != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 10, value.original_payload)
        }
        if (value.max_retry != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 7, value.max_retry)
        }
        if (value.retry_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.retry_count)
        }
        if (value.error_msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.error_msg)
        }
        if (value.error_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.error_code)
        }
        if (value.type != com.sudooom.mahjong.common.proto.CompensationCommand.CompensationType.RETRY) {
          CompensationType.ADAPTER.encodeWithTag(writer, 3, value.type)
        }
        if (value.original_trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.original_trace_id)
        }
        if (value.compensation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.compensation_id)
        }
      }

      override fun decode(reader: ProtoReader): CompensationCommand {
        var compensation_id: String = ""
        var original_trace_id: String = ""
        var type: CompensationType = CompensationType.RETRY
        var error_code: String = ""
        var error_msg: String = ""
        var retry_count: Int = 0
        var max_retry: Int = 0
        var original_payload: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> compensation_id = ProtoAdapter.STRING.decode(reader)
            2 -> original_trace_id = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              type = CompensationType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> error_code = ProtoAdapter.STRING.decode(reader)
            5 -> error_msg = ProtoAdapter.STRING.decode(reader)
            6 -> retry_count = ProtoAdapter.INT32.decode(reader)
            7 -> max_retry = ProtoAdapter.INT32.decode(reader)
            10 -> original_payload = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CompensationCommand(
          compensation_id = compensation_id,
          original_trace_id = original_trace_id,
          type = type,
          error_code = error_code,
          error_msg = error_msg,
          retry_count = retry_count,
          max_retry = max_retry,
          original_payload = original_payload,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CompensationCommand): CompensationCommand = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class CompensationType(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * 重试
     */
    RETRY(0),
    /**
     * 回滚
     */
    ROLLBACK(1),
    /**
     * 告警
     */
    ALERT(2),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<CompensationType> = object : EnumAdapter<CompensationType>(
        CompensationType::class, 
        PROTO_3, 
        CompensationType.RETRY
      ) {
        override fun fromValue(`value`: Int): CompensationType? = CompensationType.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): CompensationType? = when (`value`) {
        0 -> RETRY
        1 -> ROLLBACK
        2 -> ALERT
        else -> null
      }
    }
  }
}
