// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ErrorCode in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class ErrorCode(
  override val `value`: Int,
) : WireEnum {
  SUCCESS(0),
  UNKNOWN_ERROR(1),
  AUTH_FAILED(1_001),
  PARAM_ERROR(1_002),
  ROOM_NOT_FOUND(2_001),
  ROOM_FULL(2_002),
  NOT_IN_ROOM(2_003),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ErrorCode> = object : EnumAdapter<ErrorCode>(
      ErrorCode::class, 
      PROTO_3, 
      ErrorCode.SUCCESS
    ) {
      override fun fromValue(`value`: Int): ErrorCode? = ErrorCode.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ErrorCode? = when (`value`) {
      0 -> SUCCESS
      1 -> UNKNOWN_ERROR
      1_001 -> AUTH_FAILED
      1_002 -> PARAM_ERROR
      2_001 -> ROOM_NOT_FOUND
      2_002 -> ROOM_FULL
      2_003 -> NOT_IN_ROOM
      else -> null
    }
  }
}
