// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.GameType in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class GameType(
  override val `value`: Int,
) : WireEnum {
  GAME_TYPE_UNKNOWN(0),
  GAME_MAHJONG(1),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GameType> = object : EnumAdapter<GameType>(
      GameType::class, 
      PROTO_3, 
      GameType.GAME_TYPE_UNKNOWN
    ) {
      override fun fromValue(`value`: Int): GameType? = GameType.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): GameType? = when (`value`) {
      0 -> GAME_TYPE_UNKNOWN
      1 -> GAME_MAHJONG
      else -> null
    }
  }
}
