// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.GameReq in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class GameReq(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 0,
  )
  public val room_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.GameType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "gameType",
    schemaIndex = 1,
  )
  public val game_type: GameType = GameType.GAME_TYPE_UNKNOWN,
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.MahjongReq#ADAPTER",
    oneofName = "game_data",
    schemaIndex = 2,
  )
  public val mahjong: MahjongReq? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GameReq, Nothing>(ADAPTER, unknownFields) {
  init {
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GameReq) return false
    if (unknownFields != other.unknownFields) return false
    if (room_id != other.room_id) return false
    if (game_type != other.game_type) return false
    if (mahjong != other.mahjong) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + game_type.hashCode()
      result = result * 37 + (mahjong?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """room_id=${sanitize(room_id)}"""
    result += """game_type=$game_type"""
    if (mahjong != null) result += """mahjong=$mahjong"""
    return result.joinToString(prefix = "GameReq{", separator = ", ", postfix = "}")
  }

  public fun copy(
    room_id: String = this.room_id,
    game_type: GameType = this.game_type,
    mahjong: MahjongReq? = this.mahjong,
    unknownFields: ByteString = this.unknownFields,
  ): GameReq = GameReq(room_id, game_type, mahjong, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GameReq> = object : ProtoAdapter<GameReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      GameReq::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.GameReq", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: GameReq): Int {
        var size = value.unknownFields.size
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.room_id)
        }
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          size += GameType.ADAPTER.encodedSizeWithTag(2, value.game_type)
        }
        size += MahjongReq.ADAPTER.encodedSizeWithTag(10, value.mahjong)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GameReq) {
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          GameType.ADAPTER.encodeWithTag(writer, 2, value.game_type)
        }
        MahjongReq.ADAPTER.encodeWithTag(writer, 10, value.mahjong)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GameReq) {
        writer.writeBytes(value.unknownFields)
        MahjongReq.ADAPTER.encodeWithTag(writer, 10, value.mahjong)
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          GameType.ADAPTER.encodeWithTag(writer, 2, value.game_type)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
      }

      override fun decode(reader: ProtoReader): GameReq {
        var room_id: String = ""
        var game_type: GameType = GameType.GAME_TYPE_UNKNOWN
        var mahjong: MahjongReq? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> room_id = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              game_type = GameType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            10 -> mahjong = MahjongReq.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GameReq(
          room_id = room_id,
          game_type = game_type,
          mahjong = mahjong,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GameReq): GameReq = value.copy(
        mahjong = value.mahjong?.let(MahjongReq.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
