// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.HeartbeatResp in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class HeartbeatResp(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "serverTime",
    schemaIndex = 0,
  )
  public val server_time: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HeartbeatResp, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HeartbeatResp) return false
    if (unknownFields != other.unknownFields) return false
    if (server_time != other.server_time) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + server_time.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """server_time=$server_time"""
    return result.joinToString(prefix = "HeartbeatResp{", separator = ", ", postfix = "}")
  }

  public fun copy(server_time: Long = this.server_time, unknownFields: ByteString = this.unknownFields): HeartbeatResp = HeartbeatResp(server_time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HeartbeatResp> = object : ProtoAdapter<HeartbeatResp>(
      FieldEncoding.LENGTH_DELIMITED, 
      HeartbeatResp::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.HeartbeatResp", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: HeartbeatResp): Int {
        var size = value.unknownFields.size
        if (value.server_time != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.server_time)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: HeartbeatResp) {
        if (value.server_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.server_time)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: HeartbeatResp) {
        writer.writeBytes(value.unknownFields)
        if (value.server_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.server_time)
        }
      }

      override fun decode(reader: ProtoReader): HeartbeatResp {
        var server_time: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> server_time = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HeartbeatResp(
          server_time = server_time,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: HeartbeatResp): HeartbeatResp = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
