// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.HeartbeatReq in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class HeartbeatReq(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "clientTime",
    schemaIndex = 0,
  )
  public val client_time: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HeartbeatReq, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HeartbeatReq) return false
    if (unknownFields != other.unknownFields) return false
    if (client_time != other.client_time) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + client_time.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """client_time=$client_time"""
    return result.joinToString(prefix = "HeartbeatReq{", separator = ", ", postfix = "}")
  }

  public fun copy(client_time: Long = this.client_time, unknownFields: ByteString = this.unknownFields): HeartbeatReq = HeartbeatReq(client_time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HeartbeatReq> = object : ProtoAdapter<HeartbeatReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      HeartbeatReq::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.HeartbeatReq", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: HeartbeatReq): Int {
        var size = value.unknownFields.size
        if (value.client_time != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.client_time)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: HeartbeatReq) {
        if (value.client_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.client_time)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: HeartbeatReq) {
        writer.writeBytes(value.unknownFields)
        if (value.client_time != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.client_time)
        }
      }

      override fun decode(reader: ProtoReader): HeartbeatReq {
        var client_time: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> client_time = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HeartbeatReq(
          client_time = client_time,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: HeartbeatReq): HeartbeatReq = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
