// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.KickUser in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * 踢用户指令
 */
public class KickUser(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 0,
  )
  public val user_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val reason: String = "",
  /**
   * 是否强制踢出
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val force: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<KickUser, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is KickUser) return false
    if (unknownFields != other.unknownFields) return false
    if (user_id != other.user_id) return false
    if (reason != other.reason) return false
    if (force != other.force) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + reason.hashCode()
      result = result * 37 + force.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """user_id=${sanitize(user_id)}"""
    result += """reason=${sanitize(reason)}"""
    result += """force=$force"""
    return result.joinToString(prefix = "KickUser{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_id: String = this.user_id,
    reason: String = this.reason,
    force: Boolean = this.force,
    unknownFields: ByteString = this.unknownFields,
  ): KickUser = KickUser(user_id, reason, force, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<KickUser> = object : ProtoAdapter<KickUser>(
      FieldEncoding.LENGTH_DELIMITED, 
      KickUser::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.KickUser", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: KickUser): Int {
        var size = value.unknownFields.size
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id)
        }
        if (value.reason != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.reason)
        }
        if (value.force != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.force)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: KickUser) {
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
        if (value.reason != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.reason)
        }
        if (value.force != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.force)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: KickUser) {
        writer.writeBytes(value.unknownFields)
        if (value.force != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.force)
        }
        if (value.reason != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.reason)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
      }

      override fun decode(reader: ProtoReader): KickUser {
        var user_id: String = ""
        var reason: String = ""
        var force: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_id = ProtoAdapter.STRING.decode(reader)
            2 -> reason = ProtoAdapter.STRING.decode(reader)
            3 -> force = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return KickUser(
          user_id = user_id,
          reason = reason,
          force = force,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: KickUser): KickUser = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
