// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.LogicToAccessMsg in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ============== Logic -> Access 方向 ==============
 */
public class LogicToAccessMsg(
  /**
   * 1. 用户业务消息 (推送)
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.UserMessagePush#ADAPTER",
    jsonName = "userPush",
    oneofName = "payload",
    schemaIndex = 0,
  )
  public val user_push: UserMessagePush? = null,
  /**
   * 2. 消息确认
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.MsgAck#ADAPTER",
    oneofName = "payload",
    schemaIndex = 1,
  )
  public val ack: MsgAck? = null,
  /**
   * 3. 系统指令
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.SystemCommand#ADAPTER",
    jsonName = "systemCmd",
    oneofName = "payload",
    schemaIndex = 2,
  )
  public val system_cmd: SystemCommand? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LogicToAccessMsg, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(user_push, ack, system_cmd) <= 1) {
      "At most one of user_push, ack, system_cmd may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LogicToAccessMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (user_push != other.user_push) return false
    if (ack != other.ack) return false
    if (system_cmd != other.system_cmd) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (user_push?.hashCode() ?: 0)
      result = result * 37 + (ack?.hashCode() ?: 0)
      result = result * 37 + (system_cmd?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (user_push != null) result += """user_push=$user_push"""
    if (ack != null) result += """ack=$ack"""
    if (system_cmd != null) result += """system_cmd=$system_cmd"""
    return result.joinToString(prefix = "LogicToAccessMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_push: UserMessagePush? = this.user_push,
    ack: MsgAck? = this.ack,
    system_cmd: SystemCommand? = this.system_cmd,
    unknownFields: ByteString = this.unknownFields,
  ): LogicToAccessMsg = LogicToAccessMsg(user_push, ack, system_cmd, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LogicToAccessMsg> = object : ProtoAdapter<LogicToAccessMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      LogicToAccessMsg::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.LogicToAccessMsg", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: LogicToAccessMsg): Int {
        var size = value.unknownFields.size
        size += UserMessagePush.ADAPTER.encodedSizeWithTag(10, value.user_push)
        size += MsgAck.ADAPTER.encodedSizeWithTag(11, value.ack)
        size += SystemCommand.ADAPTER.encodedSizeWithTag(12, value.system_cmd)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LogicToAccessMsg) {
        UserMessagePush.ADAPTER.encodeWithTag(writer, 10, value.user_push)
        MsgAck.ADAPTER.encodeWithTag(writer, 11, value.ack)
        SystemCommand.ADAPTER.encodeWithTag(writer, 12, value.system_cmd)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LogicToAccessMsg) {
        writer.writeBytes(value.unknownFields)
        SystemCommand.ADAPTER.encodeWithTag(writer, 12, value.system_cmd)
        MsgAck.ADAPTER.encodeWithTag(writer, 11, value.ack)
        UserMessagePush.ADAPTER.encodeWithTag(writer, 10, value.user_push)
      }

      override fun decode(reader: ProtoReader): LogicToAccessMsg {
        var user_push: UserMessagePush? = null
        var ack: MsgAck? = null
        var system_cmd: SystemCommand? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            10 -> user_push = UserMessagePush.ADAPTER.decode(reader)
            11 -> ack = MsgAck.ADAPTER.decode(reader)
            12 -> system_cmd = SystemCommand.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LogicToAccessMsg(
          user_push = user_push,
          ack = ack,
          system_cmd = system_cmd,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LogicToAccessMsg): LogicToAccessMsg = value.copy(
        user_push = value.user_push?.let(UserMessagePush.ADAPTER::redact),
        ack = value.ack?.let(MsgAck.ADAPTER::redact),
        system_cmd = value.system_cmd?.let(SystemCommand.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
