// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MahjongTile in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class MahjongTile(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.MahjongColor#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val color: MahjongColor = MahjongColor.COLOR_UNKNOWN,
  /**
   * 1-9
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 1,
  )
  public val value_: Int = 0,
  /**
   * 1-4 (第几张)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val index: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MahjongTile, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MahjongTile) return false
    if (unknownFields != other.unknownFields) return false
    if (color != other.color) return false
    if (value_ != other.value_) return false
    if (index != other.index) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + color.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + index.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """color=$color"""
    result += """value_=$value_"""
    result += """index=$index"""
    return result.joinToString(prefix = "MahjongTile{", separator = ", ", postfix = "}")
  }

  public fun copy(
    color: MahjongColor = this.color,
    value_: Int = this.value_,
    index: Int = this.index,
    unknownFields: ByteString = this.unknownFields,
  ): MahjongTile = MahjongTile(color, value_, index, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MahjongTile> = object : ProtoAdapter<MahjongTile>(
      FieldEncoding.LENGTH_DELIMITED, 
      MahjongTile::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.MahjongTile", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: MahjongTile): Int {
        var size = value.unknownFields.size
        if (value.color != com.sudooom.mahjong.common.proto.MahjongColor.COLOR_UNKNOWN) {
          size += MahjongColor.ADAPTER.encodedSizeWithTag(1, value.color)
        }
        if (value.value_ != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.value_)
        }
        if (value.index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.index)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MahjongTile) {
        if (value.color != com.sudooom.mahjong.common.proto.MahjongColor.COLOR_UNKNOWN) {
          MahjongColor.ADAPTER.encodeWithTag(writer, 1, value.color)
        }
        if (value.value_ != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.value_)
        }
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.index)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MahjongTile) {
        writer.writeBytes(value.unknownFields)
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.index)
        }
        if (value.value_ != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.value_)
        }
        if (value.color != com.sudooom.mahjong.common.proto.MahjongColor.COLOR_UNKNOWN) {
          MahjongColor.ADAPTER.encodeWithTag(writer, 1, value.color)
        }
      }

      override fun decode(reader: ProtoReader): MahjongTile {
        var color: MahjongColor = MahjongColor.COLOR_UNKNOWN
        var value_: Int = 0
        var index: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              color = MahjongColor.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> value_ = ProtoAdapter.INT32.decode(reader)
            3 -> index = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MahjongTile(
          color = color,
          value_ = value_,
          index = index,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MahjongTile): MahjongTile = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
