// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MahjongReq in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * Mahjong Specifics
 * =============================================================================
 * 麻将请求 (Client -> Server)
 * 麻将请求 (Client -> Server)
 */
public class MahjongReq(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.MahjongReq${'$'}Action#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val action: Action = Action.DISCARD,
  /**
   * 操作的牌
   */
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val tile: MahjongTile? = null,
  /**
   * 事件和决策追踪
   * 响应的事件ID (对应 MahjongNotification.event_id)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "eventId",
    schemaIndex = 2,
  )
  public val event_id: String = "",
  /**
   * 响应的决策ID (如果是多人决策场景，如碰/杠/胡)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "decisionId",
    schemaIndex = 3,
  )
  public val decision_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MahjongReq, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MahjongReq) return false
    if (unknownFields != other.unknownFields) return false
    if (action != other.action) return false
    if (tile != other.tile) return false
    if (event_id != other.event_id) return false
    if (decision_id != other.decision_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + action.hashCode()
      result = result * 37 + (tile?.hashCode() ?: 0)
      result = result * 37 + event_id.hashCode()
      result = result * 37 + decision_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """action=$action"""
    if (tile != null) result += """tile=$tile"""
    result += """event_id=${sanitize(event_id)}"""
    result += """decision_id=${sanitize(decision_id)}"""
    return result.joinToString(prefix = "MahjongReq{", separator = ", ", postfix = "}")
  }

  public fun copy(
    action: Action = this.action,
    tile: MahjongTile? = this.tile,
    event_id: String = this.event_id,
    decision_id: String = this.decision_id,
    unknownFields: ByteString = this.unknownFields,
  ): MahjongReq = MahjongReq(action, tile, event_id, decision_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MahjongReq> = object : ProtoAdapter<MahjongReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      MahjongReq::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.MahjongReq", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: MahjongReq): Int {
        var size = value.unknownFields.size
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          size += Action.ADAPTER.encodedSizeWithTag(1, value.action)
        }
        if (value.tile != null) {
          size += MahjongTile.ADAPTER.encodedSizeWithTag(2, value.tile)
        }
        if (value.event_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.event_id)
        }
        if (value.decision_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.decision_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MahjongReq) {
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          Action.ADAPTER.encodeWithTag(writer, 1, value.action)
        }
        if (value.tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 2, value.tile)
        }
        if (value.event_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.event_id)
        }
        if (value.decision_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.decision_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MahjongReq) {
        writer.writeBytes(value.unknownFields)
        if (value.decision_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.decision_id)
        }
        if (value.event_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.event_id)
        }
        if (value.tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 2, value.tile)
        }
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          Action.ADAPTER.encodeWithTag(writer, 1, value.action)
        }
      }

      override fun decode(reader: ProtoReader): MahjongReq {
        var action: Action = Action.DISCARD
        var tile: MahjongTile? = null
        var event_id: String = ""
        var decision_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              action = Action.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> tile = MahjongTile.ADAPTER.decode(reader)
            3 -> event_id = ProtoAdapter.STRING.decode(reader)
            4 -> decision_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MahjongReq(
          action = action,
          tile = tile,
          event_id = event_id,
          decision_id = decision_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MahjongReq): MahjongReq = value.copy(
        tile = value.tile?.let(MahjongTile.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Action(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * 出牌
     */
    DISCARD(0),
    PONG(1),
    KONG(2),
    /**
     * 胡 (点炮)
     */
    HU(3),
    /**
     * 自摸
     */
    ZI_MO(4),
    /**
     * 托管
     */
    AUTO(5),
    /**
     * 过 (放弃操作)
     */
    PASS(6),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Action> = object : EnumAdapter<Action>(
        Action::class, 
        PROTO_3, 
        Action.DISCARD
      ) {
        override fun fromValue(`value`: Int): Action? = Action.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Action? = when (`value`) {
        0 -> DISCARD
        1 -> PONG
        2 -> KONG
        3 -> HU
        4 -> ZI_MO
        5 -> AUTO
        6 -> PASS
        else -> null
      }
    }
  }
}
