// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MahjongNotification in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * 麻将通知 (Server -> Client)
 */
public class MahjongNotification(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.MahjongNotification${'$'}Type#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: Type = Type.GAME_START,
  /**
   * 事件和决策追踪
   * 事件唯一ID，客户端响应时需要携带
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "eventId",
    schemaIndex = 1,
  )
  public val event_id: String = "",
  /**
   * 决策ID (仅在 ASK_ACTION 时有值，用于多人决策场景)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "decisionId",
    schemaIndex = 2,
  )
  public val decision_id: String = "",
  /**
   * State Data
   * 剩余牌数
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "remainCards",
    schemaIndex = 3,
  )
  public val remain_cards: Int = 0,
  /**
   * 当前操作者座位
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currentSeat",
    schemaIndex = 4,
  )
  public val current_seat: Int = 0,
  /**
   * 倒计时
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val countdown: Int = 0,
  /**
   * For TURN_CHANGE (Private to current player)
   * 摸到的牌 (仅推送给当前玩家，其他玩家此字段为空)
   */
  @field:WireField(
    tag = 7,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "drawnTile",
    schemaIndex = 6,
  )
  public val drawn_tile: MahjongTile? = null,
  /**
   * For ACTION_RESULT
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "actionUserId",
    schemaIndex = 7,
  )
  public val action_user_id: String = "",
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "actionSeat",
    schemaIndex = 8,
  )
  public val action_seat: Int = 0,
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.MahjongReq${'$'}Action#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 9,
  )
  public val action: MahjongReq.Action = MahjongReq.Action.DISCARD,
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val tile: MahjongTile? = null,
  related_tiles: List<MahjongTile> = emptyList(),
  allowed_actions: List<MahjongReq.Action> = emptyList(),
  hand_tiles: List<MahjongTile> = emptyList(),
  players_public_info: List<PlayerPublicInfo> = emptyList(),
  /**
   * For SETTLEMENT
   * 结算详情
   */
  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "settlementJson",
    schemaIndex = 15,
  )
  public val settlement_json: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MahjongNotification, Nothing>(ADAPTER, unknownFields) {
  /**
   * 碰/杠 相关的牌
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "relatedTiles",
    schemaIndex = 11,
  )
  public val related_tiles: List<MahjongTile> = immutableCopyOf("related_tiles", related_tiles)

  /**
   * For ASK_ACTION (Private to user)
   */
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.MahjongReq${'$'}Action#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "allowedActions",
    schemaIndex = 12,
  )
  public val allowed_actions: List<MahjongReq.Action> =
      immutableCopyOf("allowed_actions", allowed_actions)

  /**
   * For GAME_START / SYNC
   * 私有手牌（仅推送给对应玩家）
   */
  @field:WireField(
    tag = 14,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "handTiles",
    schemaIndex = 13,
  )
  public val hand_tiles: List<MahjongTile> = immutableCopyOf("hand_tiles", hand_tiles)

  /**
   * 所有玩家的公开信息
   */
  @field:WireField(
    tag = 15,
    adapter = "com.sudooom.mahjong.common.proto.PlayerPublicInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "playersPublicInfo",
    schemaIndex = 14,
  )
  public val players_public_info: List<PlayerPublicInfo> =
      immutableCopyOf("players_public_info", players_public_info)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MahjongNotification) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (event_id != other.event_id) return false
    if (decision_id != other.decision_id) return false
    if (remain_cards != other.remain_cards) return false
    if (current_seat != other.current_seat) return false
    if (countdown != other.countdown) return false
    if (drawn_tile != other.drawn_tile) return false
    if (action_user_id != other.action_user_id) return false
    if (action_seat != other.action_seat) return false
    if (action != other.action) return false
    if (tile != other.tile) return false
    if (related_tiles != other.related_tiles) return false
    if (allowed_actions != other.allowed_actions) return false
    if (hand_tiles != other.hand_tiles) return false
    if (players_public_info != other.players_public_info) return false
    if (settlement_json != other.settlement_json) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + event_id.hashCode()
      result = result * 37 + decision_id.hashCode()
      result = result * 37 + remain_cards.hashCode()
      result = result * 37 + current_seat.hashCode()
      result = result * 37 + countdown.hashCode()
      result = result * 37 + (drawn_tile?.hashCode() ?: 0)
      result = result * 37 + action_user_id.hashCode()
      result = result * 37 + action_seat.hashCode()
      result = result * 37 + action.hashCode()
      result = result * 37 + (tile?.hashCode() ?: 0)
      result = result * 37 + related_tiles.hashCode()
      result = result * 37 + allowed_actions.hashCode()
      result = result * 37 + hand_tiles.hashCode()
      result = result * 37 + players_public_info.hashCode()
      result = result * 37 + settlement_json.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=$type"""
    result += """event_id=${sanitize(event_id)}"""
    result += """decision_id=${sanitize(decision_id)}"""
    result += """remain_cards=$remain_cards"""
    result += """current_seat=$current_seat"""
    result += """countdown=$countdown"""
    if (drawn_tile != null) result += """drawn_tile=$drawn_tile"""
    result += """action_user_id=${sanitize(action_user_id)}"""
    result += """action_seat=$action_seat"""
    result += """action=$action"""
    if (tile != null) result += """tile=$tile"""
    if (related_tiles.isNotEmpty()) result += """related_tiles=$related_tiles"""
    if (allowed_actions.isNotEmpty()) result += """allowed_actions=$allowed_actions"""
    if (hand_tiles.isNotEmpty()) result += """hand_tiles=$hand_tiles"""
    if (players_public_info.isNotEmpty()) result += """players_public_info=$players_public_info"""
    result += """settlement_json=${sanitize(settlement_json)}"""
    return result.joinToString(prefix = "MahjongNotification{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: Type = this.type,
    event_id: String = this.event_id,
    decision_id: String = this.decision_id,
    remain_cards: Int = this.remain_cards,
    current_seat: Int = this.current_seat,
    countdown: Int = this.countdown,
    drawn_tile: MahjongTile? = this.drawn_tile,
    action_user_id: String = this.action_user_id,
    action_seat: Int = this.action_seat,
    action: MahjongReq.Action = this.action,
    tile: MahjongTile? = this.tile,
    related_tiles: List<MahjongTile> = this.related_tiles,
    allowed_actions: List<MahjongReq.Action> = this.allowed_actions,
    hand_tiles: List<MahjongTile> = this.hand_tiles,
    players_public_info: List<PlayerPublicInfo> = this.players_public_info,
    settlement_json: String = this.settlement_json,
    unknownFields: ByteString = this.unknownFields,
  ): MahjongNotification = MahjongNotification(type, event_id, decision_id, remain_cards, current_seat, countdown, drawn_tile, action_user_id, action_seat, action, tile, related_tiles, allowed_actions, hand_tiles, players_public_info, settlement_json, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MahjongNotification> =
        object : ProtoAdapter<MahjongNotification>(
      FieldEncoding.LENGTH_DELIMITED, 
      MahjongNotification::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.MahjongNotification", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: MahjongNotification): Int {
        var size = value.unknownFields.size
        if (value.type != com.sudooom.mahjong.common.proto.MahjongNotification.Type.GAME_START) {
          size += Type.ADAPTER.encodedSizeWithTag(1, value.type)
        }
        if (value.event_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.event_id)
        }
        if (value.decision_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.decision_id)
        }
        if (value.remain_cards != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.remain_cards)
        }
        if (value.current_seat != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.current_seat)
        }
        if (value.countdown != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.countdown)
        }
        if (value.drawn_tile != null) {
          size += MahjongTile.ADAPTER.encodedSizeWithTag(7, value.drawn_tile)
        }
        if (value.action_user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.action_user_id)
        }
        if (value.action_seat != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(9, value.action_seat)
        }
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          size += MahjongReq.Action.ADAPTER.encodedSizeWithTag(10, value.action)
        }
        if (value.tile != null) {
          size += MahjongTile.ADAPTER.encodedSizeWithTag(11, value.tile)
        }
        size += MahjongTile.ADAPTER.asRepeated().encodedSizeWithTag(12, value.related_tiles)
        size += MahjongReq.Action.ADAPTER.asRepeated().encodedSizeWithTag(13, value.allowed_actions)
        size += MahjongTile.ADAPTER.asRepeated().encodedSizeWithTag(14, value.hand_tiles)
        size += PlayerPublicInfo.ADAPTER.asRepeated().encodedSizeWithTag(15, value.players_public_info)
        if (value.settlement_json != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(16, value.settlement_json)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MahjongNotification) {
        if (value.type != com.sudooom.mahjong.common.proto.MahjongNotification.Type.GAME_START) {
          Type.ADAPTER.encodeWithTag(writer, 1, value.type)
        }
        if (value.event_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.event_id)
        }
        if (value.decision_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.decision_id)
        }
        if (value.remain_cards != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.remain_cards)
        }
        if (value.current_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.current_seat)
        }
        if (value.countdown != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.countdown)
        }
        if (value.drawn_tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 7, value.drawn_tile)
        }
        if (value.action_user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.action_user_id)
        }
        if (value.action_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 9, value.action_seat)
        }
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          MahjongReq.Action.ADAPTER.encodeWithTag(writer, 10, value.action)
        }
        if (value.tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 11, value.tile)
        }
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 12, value.related_tiles)
        MahjongReq.Action.ADAPTER.asRepeated().encodeWithTag(writer, 13, value.allowed_actions)
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 14, value.hand_tiles)
        PlayerPublicInfo.ADAPTER.asRepeated().encodeWithTag(writer, 15, value.players_public_info)
        if (value.settlement_json != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.settlement_json)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MahjongNotification) {
        writer.writeBytes(value.unknownFields)
        if (value.settlement_json != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.settlement_json)
        }
        PlayerPublicInfo.ADAPTER.asRepeated().encodeWithTag(writer, 15, value.players_public_info)
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 14, value.hand_tiles)
        MahjongReq.Action.ADAPTER.asRepeated().encodeWithTag(writer, 13, value.allowed_actions)
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 12, value.related_tiles)
        if (value.tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 11, value.tile)
        }
        if (value.action != com.sudooom.mahjong.common.proto.MahjongReq.Action.DISCARD) {
          MahjongReq.Action.ADAPTER.encodeWithTag(writer, 10, value.action)
        }
        if (value.action_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 9, value.action_seat)
        }
        if (value.action_user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.action_user_id)
        }
        if (value.drawn_tile != null) {
          MahjongTile.ADAPTER.encodeWithTag(writer, 7, value.drawn_tile)
        }
        if (value.countdown != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.countdown)
        }
        if (value.current_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.current_seat)
        }
        if (value.remain_cards != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.remain_cards)
        }
        if (value.decision_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.decision_id)
        }
        if (value.event_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.event_id)
        }
        if (value.type != com.sudooom.mahjong.common.proto.MahjongNotification.Type.GAME_START) {
          Type.ADAPTER.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): MahjongNotification {
        var type: Type = Type.GAME_START
        var event_id: String = ""
        var decision_id: String = ""
        var remain_cards: Int = 0
        var current_seat: Int = 0
        var countdown: Int = 0
        var drawn_tile: MahjongTile? = null
        var action_user_id: String = ""
        var action_seat: Int = 0
        var action: MahjongReq.Action = MahjongReq.Action.DISCARD
        var tile: MahjongTile? = null
        val related_tiles = mutableListOf<MahjongTile>()
        val allowed_actions = mutableListOf<MahjongReq.Action>()
        val hand_tiles = mutableListOf<MahjongTile>()
        val players_public_info = mutableListOf<PlayerPublicInfo>()
        var settlement_json: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              type = Type.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> event_id = ProtoAdapter.STRING.decode(reader)
            3 -> decision_id = ProtoAdapter.STRING.decode(reader)
            4 -> remain_cards = ProtoAdapter.INT32.decode(reader)
            5 -> current_seat = ProtoAdapter.INT32.decode(reader)
            6 -> countdown = ProtoAdapter.INT32.decode(reader)
            7 -> drawn_tile = MahjongTile.ADAPTER.decode(reader)
            8 -> action_user_id = ProtoAdapter.STRING.decode(reader)
            9 -> action_seat = ProtoAdapter.INT32.decode(reader)
            10 -> try {
              action = MahjongReq.Action.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            11 -> tile = MahjongTile.ADAPTER.decode(reader)
            12 -> related_tiles.add(MahjongTile.ADAPTER.decode(reader))
            13 -> try {
              MahjongReq.Action.ADAPTER.tryDecode(reader, allowed_actions)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            14 -> hand_tiles.add(MahjongTile.ADAPTER.decode(reader))
            15 -> players_public_info.add(PlayerPublicInfo.ADAPTER.decode(reader))
            16 -> settlement_json = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MahjongNotification(
          type = type,
          event_id = event_id,
          decision_id = decision_id,
          remain_cards = remain_cards,
          current_seat = current_seat,
          countdown = countdown,
          drawn_tile = drawn_tile,
          action_user_id = action_user_id,
          action_seat = action_seat,
          action = action,
          tile = tile,
          related_tiles = related_tiles,
          allowed_actions = allowed_actions,
          hand_tiles = hand_tiles,
          players_public_info = players_public_info,
          settlement_json = settlement_json,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MahjongNotification): MahjongNotification = value.copy(
        drawn_tile = value.drawn_tile?.let(MahjongTile.ADAPTER::redact),
        tile = value.tile?.let(MahjongTile.ADAPTER::redact),
        related_tiles = value.related_tiles.redactElements(MahjongTile.ADAPTER),
        hand_tiles = value.hand_tiles.redactElements(MahjongTile.ADAPTER),
        players_public_info = value.players_public_info.redactElements(PlayerPublicInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Type(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * 游戏开始 (发牌)
     */
    GAME_START(0),
    /**
     * 轮到某人
     */
    TURN_CHANGE(1),
    /**
     * 某人做了动作 (出牌/碰/杠/胡)
     */
    ACTION_RESULT(2),
    /**
     * 询问玩家操作 (是否碰/杠/胡)
     */
    ASK_ACTION(3),
    /**
     * 单局结算
     */
    GAME_SETTLEMENT(4),
    /**
     * 总结算
     */
    GAME_TOTAL_RESULT(5),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Type> = object : EnumAdapter<Type>(
        Type::class, 
        PROTO_3, 
        Type.GAME_START
      ) {
        override fun fromValue(`value`: Int): Type? = Type.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Type? = when (`value`) {
        0 -> GAME_START
        1 -> TURN_CHANGE
        2 -> ACTION_RESULT
        3 -> ASK_ACTION
        4 -> GAME_SETTLEMENT
        5 -> GAME_TOTAL_RESULT
        else -> null
      }
    }
  }
}
