// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MahjongColor in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class MahjongColor(
  override val `value`: Int,
) : WireEnum {
  COLOR_UNKNOWN(0),
  MAN(1),
  SUO(2),
  PIN(3),
  /**
   * 字 (风/箭) - Optional but good practice
   */
  HONORS(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MahjongColor> = object : EnumAdapter<MahjongColor>(
      MahjongColor::class, 
      PROTO_3, 
      MahjongColor.COLOR_UNKNOWN
    ) {
      override fun fromValue(`value`: Int): MahjongColor? = MahjongColor.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): MahjongColor? = when (`value`) {
      0 -> COLOR_UNKNOWN
      1 -> MAN
      2 -> SUO
      3 -> PIN
      4 -> HONORS
      else -> null
    }
  }
}
