// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MeldGroup in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * 牌组类型（碰、杠、吃）
 */
public class MeldGroup(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.MeldGroup${'$'}MeldType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: MeldType = MeldType.PONG,
  tiles: List<MahjongTile> = emptyList(),
  /**
   * 来自哪个座位的牌（碰杠时有效，-1表示自己摸的）
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "fromSeat",
    schemaIndex = 2,
  )
  public val from_seat: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MeldGroup, Nothing>(ADAPTER, unknownFields) {
  /**
   * 牌组中的牌
   */
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val tiles: List<MahjongTile> = immutableCopyOf("tiles", tiles)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MeldGroup) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (tiles != other.tiles) return false
    if (from_seat != other.from_seat) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + tiles.hashCode()
      result = result * 37 + from_seat.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=$type"""
    if (tiles.isNotEmpty()) result += """tiles=$tiles"""
    result += """from_seat=$from_seat"""
    return result.joinToString(prefix = "MeldGroup{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: MeldType = this.type,
    tiles: List<MahjongTile> = this.tiles,
    from_seat: Int = this.from_seat,
    unknownFields: ByteString = this.unknownFields,
  ): MeldGroup = MeldGroup(type, tiles, from_seat, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MeldGroup> = object : ProtoAdapter<MeldGroup>(
      FieldEncoding.LENGTH_DELIMITED, 
      MeldGroup::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.MeldGroup", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: MeldGroup): Int {
        var size = value.unknownFields.size
        if (value.type != com.sudooom.mahjong.common.proto.MeldGroup.MeldType.PONG) {
          size += MeldType.ADAPTER.encodedSizeWithTag(1, value.type)
        }
        size += MahjongTile.ADAPTER.asRepeated().encodedSizeWithTag(2, value.tiles)
        if (value.from_seat != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.from_seat)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MeldGroup) {
        if (value.type != com.sudooom.mahjong.common.proto.MeldGroup.MeldType.PONG) {
          MeldType.ADAPTER.encodeWithTag(writer, 1, value.type)
        }
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.tiles)
        if (value.from_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.from_seat)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MeldGroup) {
        writer.writeBytes(value.unknownFields)
        if (value.from_seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.from_seat)
        }
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.tiles)
        if (value.type != com.sudooom.mahjong.common.proto.MeldGroup.MeldType.PONG) {
          MeldType.ADAPTER.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): MeldGroup {
        var type: MeldType = MeldType.PONG
        val tiles = mutableListOf<MahjongTile>()
        var from_seat: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              type = MeldType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> tiles.add(MahjongTile.ADAPTER.decode(reader))
            3 -> from_seat = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MeldGroup(
          type = type,
          tiles = tiles,
          from_seat = from_seat,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MeldGroup): MeldGroup = value.copy(
        tiles = value.tiles.redactElements(MahjongTile.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class MeldType(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * 碰（3张相同）
     */
    PONG(0),
    /**
     * 明杠（4张相同，别人打的）
     */
    KONG(1),
    /**
     * 暗杠（4张相同，自己摸的）
     */
    CONCEALED_KONG(2),
    /**
     * 吃（顺子，123、234等）
     */
    CHOW(3),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<MeldType> = object : EnumAdapter<MeldType>(
        MeldType::class, 
        PROTO_3, 
        MeldType.PONG
      ) {
        override fun fromValue(`value`: Int): MeldType? = MeldType.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): MeldType? = when (`value`) {
        0 -> PONG
        1 -> KONG
        2 -> CONCEALED_KONG
        3 -> CHOW
        else -> null
      }
    }
  }
}
