// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MsgAck in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ========== 2. 消息确认 (ACK) ==========
 */
public class MsgAck(
  /**
   * ACK ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ackId",
    schemaIndex = 0,
  )
  public val ack_id: String = "",
  /**
   * 原始消息ID
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "originalMsgId",
    schemaIndex = 1,
  )
  public val original_msg_id: String = "",
  /**
   * 原始追踪ID
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "originalTraceId",
    schemaIndex = 2,
  )
  public val original_trace_id: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.sudooom.mahjong.common.proto.MsgAck${'$'}AckType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ackType",
    schemaIndex = 3,
  )
  public val ack_type: AckType = AckType.RECEIVED,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val timestamp: Long = 0L,
  /**
   * 如果失败，提供错误信息
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "errorCode",
    schemaIndex = 5,
  )
  public val error_code: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "errorMsg",
    schemaIndex = 6,
  )
  public val error_msg: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MsgAck, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MsgAck) return false
    if (unknownFields != other.unknownFields) return false
    if (ack_id != other.ack_id) return false
    if (original_msg_id != other.original_msg_id) return false
    if (original_trace_id != other.original_trace_id) return false
    if (ack_type != other.ack_type) return false
    if (timestamp != other.timestamp) return false
    if (error_code != other.error_code) return false
    if (error_msg != other.error_msg) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ack_id.hashCode()
      result = result * 37 + original_msg_id.hashCode()
      result = result * 37 + original_trace_id.hashCode()
      result = result * 37 + ack_type.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + error_code.hashCode()
      result = result * 37 + error_msg.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ack_id=${sanitize(ack_id)}"""
    result += """original_msg_id=${sanitize(original_msg_id)}"""
    result += """original_trace_id=${sanitize(original_trace_id)}"""
    result += """ack_type=$ack_type"""
    result += """timestamp=$timestamp"""
    result += """error_code=${sanitize(error_code)}"""
    result += """error_msg=${sanitize(error_msg)}"""
    return result.joinToString(prefix = "MsgAck{", separator = ", ", postfix = "}")
  }

  public fun copy(
    ack_id: String = this.ack_id,
    original_msg_id: String = this.original_msg_id,
    original_trace_id: String = this.original_trace_id,
    ack_type: AckType = this.ack_type,
    timestamp: Long = this.timestamp,
    error_code: String = this.error_code,
    error_msg: String = this.error_msg,
    unknownFields: ByteString = this.unknownFields,
  ): MsgAck = MsgAck(ack_id, original_msg_id, original_trace_id, ack_type, timestamp, error_code, error_msg, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MsgAck> = object : ProtoAdapter<MsgAck>(
      FieldEncoding.LENGTH_DELIMITED, 
      MsgAck::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.MsgAck", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: MsgAck): Int {
        var size = value.unknownFields.size
        if (value.ack_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.ack_id)
        }
        if (value.original_msg_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.original_msg_id)
        }
        if (value.original_trace_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.original_trace_id)
        }
        if (value.ack_type != com.sudooom.mahjong.common.proto.MsgAck.AckType.RECEIVED) {
          size += AckType.ADAPTER.encodedSizeWithTag(4, value.ack_type)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(5, value.timestamp)
        }
        if (value.error_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.error_code)
        }
        if (value.error_msg != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.error_msg)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MsgAck) {
        if (value.ack_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ack_id)
        }
        if (value.original_msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.original_msg_id)
        }
        if (value.original_trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.original_trace_id)
        }
        if (value.ack_type != com.sudooom.mahjong.common.proto.MsgAck.AckType.RECEIVED) {
          AckType.ADAPTER.encodeWithTag(writer, 4, value.ack_type)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 5, value.timestamp)
        }
        if (value.error_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.error_code)
        }
        if (value.error_msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.error_msg)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MsgAck) {
        writer.writeBytes(value.unknownFields)
        if (value.error_msg != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.error_msg)
        }
        if (value.error_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.error_code)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 5, value.timestamp)
        }
        if (value.ack_type != com.sudooom.mahjong.common.proto.MsgAck.AckType.RECEIVED) {
          AckType.ADAPTER.encodeWithTag(writer, 4, value.ack_type)
        }
        if (value.original_trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.original_trace_id)
        }
        if (value.original_msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.original_msg_id)
        }
        if (value.ack_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ack_id)
        }
      }

      override fun decode(reader: ProtoReader): MsgAck {
        var ack_id: String = ""
        var original_msg_id: String = ""
        var original_trace_id: String = ""
        var ack_type: AckType = AckType.RECEIVED
        var timestamp: Long = 0L
        var error_code: String = ""
        var error_msg: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ack_id = ProtoAdapter.STRING.decode(reader)
            2 -> original_msg_id = ProtoAdapter.STRING.decode(reader)
            3 -> original_trace_id = ProtoAdapter.STRING.decode(reader)
            4 -> try {
              ack_type = AckType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            5 -> timestamp = ProtoAdapter.INT64.decode(reader)
            6 -> error_code = ProtoAdapter.STRING.decode(reader)
            7 -> error_msg = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MsgAck(
          ack_id = ack_id,
          original_msg_id = original_msg_id,
          original_trace_id = original_trace_id,
          ack_type = ack_type,
          timestamp = timestamp,
          error_code = error_code,
          error_msg = error_msg,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MsgAck): MsgAck = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class AckType(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * 已收到
     */
    RECEIVED(0),
    /**
     * 已处理
     */
    PROCESSED(1),
    /**
     * 已投递给客户端
     */
    DELIVERED(2),
    /**
     * 失败
     */
    FAILED(3),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<AckType> = object : EnumAdapter<AckType>(
        AckType::class, 
        PROTO_3, 
        AckType.RECEIVED
      ) {
        override fun fromValue(`value`: Int): AckType? = AckType.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): AckType? = when (`value`) {
        0 -> RECEIVED
        1 -> PROCESSED
        2 -> DELIVERED
        3 -> FAILED
        else -> null
      }
    }
  }
}
