// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.MsgType in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class MsgType(
  override val `value`: Int,
) : WireEnum {
  MSG_TYPE_UNKNOWN(0),
  TEXT(1),
  IMAGE(2),
  VOICE(3),
  VIDEO(4),
  FILE(5),
  EMOJI(6),
  /**
   * 指令消息 (撤回等)
   */
  CMD(7),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MsgType> = object : EnumAdapter<MsgType>(
      MsgType::class, 
      PROTO_3, 
      MsgType.MSG_TYPE_UNKNOWN
    ) {
      override fun fromValue(`value`: Int): MsgType? = MsgType.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): MsgType? = when (`value`) {
      0 -> MSG_TYPE_UNKNOWN
      1 -> TEXT
      2 -> IMAGE
      3 -> VOICE
      4 -> VIDEO
      5 -> FILE
      6 -> EMOJI
      7 -> CMD
      else -> null
    }
  }
}
