// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.Platform in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * =============================================================================
 * Enums
 * =============================================================================
 */
public enum class Platform(
  override val `value`: Int,
) : WireEnum {
  PLATFORM_UNKNOWN(0),
  ANDROID(1),
  IOS(2),
  WEB(3),
  DESKTOP(4),
  WECHAT(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Platform> = object : EnumAdapter<Platform>(
      Platform::class, 
      PROTO_3, 
      Platform.PLATFORM_UNKNOWN
    ) {
      override fun fromValue(`value`: Int): Platform? = Platform.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Platform? = when (`value`) {
      0 -> PLATFORM_UNKNOWN
      1 -> ANDROID
      2 -> IOS
      3 -> WEB
      4 -> DESKTOP
      5 -> WECHAT
      else -> null
    }
  }
}
