// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.PlayerPublicInfo in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * 玩家公开信息（所有玩家都能看到）
 */
public class PlayerPublicInfo(
  /**
   * 座位号
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val seat: Int = 0,
  /**
   * 用户ID
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 1,
  )
  public val user_id: String = "",
  melds: List<MeldGroup> = emptyList(),
  discarded: List<MahjongTile> = emptyList(),
  /**
   * 手牌数量（不显示具体牌）
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "handCount",
    schemaIndex = 4,
  )
  public val hand_count: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PlayerPublicInfo, Nothing>(ADAPTER, unknownFields) {
  /**
   * 碰、杠、吃的牌组
   */
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.MeldGroup#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val melds: List<MeldGroup> = immutableCopyOf("melds", melds)

  /**
   * 打出的牌（按时间顺序）
   */
  @field:WireField(
    tag = 4,
    adapter = "com.sudooom.mahjong.common.proto.MahjongTile#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val discarded: List<MahjongTile> = immutableCopyOf("discarded", discarded)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PlayerPublicInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (seat != other.seat) return false
    if (user_id != other.user_id) return false
    if (melds != other.melds) return false
    if (discarded != other.discarded) return false
    if (hand_count != other.hand_count) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + seat.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + melds.hashCode()
      result = result * 37 + discarded.hashCode()
      result = result * 37 + hand_count.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """seat=$seat"""
    result += """user_id=${sanitize(user_id)}"""
    if (melds.isNotEmpty()) result += """melds=$melds"""
    if (discarded.isNotEmpty()) result += """discarded=$discarded"""
    result += """hand_count=$hand_count"""
    return result.joinToString(prefix = "PlayerPublicInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    seat: Int = this.seat,
    user_id: String = this.user_id,
    melds: List<MeldGroup> = this.melds,
    discarded: List<MahjongTile> = this.discarded,
    hand_count: Int = this.hand_count,
    unknownFields: ByteString = this.unknownFields,
  ): PlayerPublicInfo = PlayerPublicInfo(seat, user_id, melds, discarded, hand_count, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PlayerPublicInfo> = object : ProtoAdapter<PlayerPublicInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      PlayerPublicInfo::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.PlayerPublicInfo", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: PlayerPublicInfo): Int {
        var size = value.unknownFields.size
        if (value.seat != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.seat)
        }
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.user_id)
        }
        size += MeldGroup.ADAPTER.asRepeated().encodedSizeWithTag(3, value.melds)
        size += MahjongTile.ADAPTER.asRepeated().encodedSizeWithTag(4, value.discarded)
        if (value.hand_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.hand_count)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PlayerPublicInfo) {
        if (value.seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.seat)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.user_id)
        }
        MeldGroup.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.melds)
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.discarded)
        if (value.hand_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.hand_count)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PlayerPublicInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.hand_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.hand_count)
        }
        MahjongTile.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.discarded)
        MeldGroup.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.melds)
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.user_id)
        }
        if (value.seat != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.seat)
        }
      }

      override fun decode(reader: ProtoReader): PlayerPublicInfo {
        var seat: Int = 0
        var user_id: String = ""
        val melds = mutableListOf<MeldGroup>()
        val discarded = mutableListOf<MahjongTile>()
        var hand_count: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> seat = ProtoAdapter.INT32.decode(reader)
            2 -> user_id = ProtoAdapter.STRING.decode(reader)
            3 -> melds.add(MeldGroup.ADAPTER.decode(reader))
            4 -> discarded.add(MahjongTile.ADAPTER.decode(reader))
            5 -> hand_count = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PlayerPublicInfo(
          seat = seat,
          user_id = user_id,
          melds = melds,
          discarded = discarded,
          hand_count = hand_count,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PlayerPublicInfo): PlayerPublicInfo = value.copy(
        melds = value.melds.redactElements(MeldGroup.ADAPTER),
        discarded = value.discarded.redactElements(MahjongTile.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
