// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.RoomPush in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class RoomPush(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.RoomPush${'$'}Event#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val event: Event = Event.USER_JOINED,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 1,
  )
  public val room_id: String = "",
  /**
   * 触发事件的用户
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 2,
  )
  public val user_id: String = "",
  /**
   * 最新的房间信息
   */
  @field:WireField(
    tag = 4,
    adapter = "com.sudooom.mahjong.common.proto.RoomInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomInfo",
    schemaIndex = 3,
  )
  public val room_info: RoomInfo? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RoomPush, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RoomPush) return false
    if (unknownFields != other.unknownFields) return false
    if (event != other.event) return false
    if (room_id != other.room_id) return false
    if (user_id != other.user_id) return false
    if (room_info != other.room_info) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + event.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + (room_info?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """event=$event"""
    result += """room_id=${sanitize(room_id)}"""
    result += """user_id=${sanitize(user_id)}"""
    if (room_info != null) result += """room_info=$room_info"""
    return result.joinToString(prefix = "RoomPush{", separator = ", ", postfix = "}")
  }

  public fun copy(
    event: Event = this.event,
    room_id: String = this.room_id,
    user_id: String = this.user_id,
    room_info: RoomInfo? = this.room_info,
    unknownFields: ByteString = this.unknownFields,
  ): RoomPush = RoomPush(event, room_id, user_id, room_info, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RoomPush> = object : ProtoAdapter<RoomPush>(
      FieldEncoding.LENGTH_DELIMITED, 
      RoomPush::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.RoomPush", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: RoomPush): Int {
        var size = value.unknownFields.size
        if (value.event != com.sudooom.mahjong.common.proto.RoomPush.Event.USER_JOINED) {
          size += Event.ADAPTER.encodedSizeWithTag(1, value.event)
        }
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.room_id)
        }
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.user_id)
        }
        if (value.room_info != null) {
          size += RoomInfo.ADAPTER.encodedSizeWithTag(4, value.room_info)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RoomPush) {
        if (value.event != com.sudooom.mahjong.common.proto.RoomPush.Event.USER_JOINED) {
          Event.ADAPTER.encodeWithTag(writer, 1, value.event)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.room_id)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.user_id)
        }
        if (value.room_info != null) {
          RoomInfo.ADAPTER.encodeWithTag(writer, 4, value.room_info)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RoomPush) {
        writer.writeBytes(value.unknownFields)
        if (value.room_info != null) {
          RoomInfo.ADAPTER.encodeWithTag(writer, 4, value.room_info)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.user_id)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.room_id)
        }
        if (value.event != com.sudooom.mahjong.common.proto.RoomPush.Event.USER_JOINED) {
          Event.ADAPTER.encodeWithTag(writer, 1, value.event)
        }
      }

      override fun decode(reader: ProtoReader): RoomPush {
        var event: Event = Event.USER_JOINED
        var room_id: String = ""
        var user_id: String = ""
        var room_info: RoomInfo? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              event = Event.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> room_id = ProtoAdapter.STRING.decode(reader)
            3 -> user_id = ProtoAdapter.STRING.decode(reader)
            4 -> room_info = RoomInfo.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RoomPush(
          event = event,
          room_id = room_id,
          user_id = user_id,
          room_info = room_info,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RoomPush): RoomPush = value.copy(
        room_info = value.room_info?.let(RoomInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Event(
    override val `value`: Int,
  ) : WireEnum {
    USER_JOINED(0),
    USER_LEFT(1),
    USER_READY(2),
    GAME_START(3),
    GAME_OVER(4),
    ROOM_DISMISSED(5),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Event> = object : EnumAdapter<Event>(
        Event::class, 
        PROTO_3, 
        Event.USER_JOINED
      ) {
        override fun fromValue(`value`: Int): Event? = Event.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Event? = when (`value`) {
        0 -> USER_JOINED
        1 -> USER_LEFT
        2 -> USER_READY
        3 -> GAME_START
        4 -> GAME_OVER
        5 -> ROOM_DISMISSED
        else -> null
      }
    }
  }
}
