// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.RoomResp in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class RoomResp(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 0,
  )
  public val room_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.RoomInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomInfo",
    schemaIndex = 1,
  )
  public val room_info: RoomInfo? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RoomResp, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RoomResp) return false
    if (unknownFields != other.unknownFields) return false
    if (room_id != other.room_id) return false
    if (room_info != other.room_info) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + (room_info?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """room_id=${sanitize(room_id)}"""
    if (room_info != null) result += """room_info=$room_info"""
    return result.joinToString(prefix = "RoomResp{", separator = ", ", postfix = "}")
  }

  public fun copy(
    room_id: String = this.room_id,
    room_info: RoomInfo? = this.room_info,
    unknownFields: ByteString = this.unknownFields,
  ): RoomResp = RoomResp(room_id, room_info, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RoomResp> = object : ProtoAdapter<RoomResp>(
      FieldEncoding.LENGTH_DELIMITED, 
      RoomResp::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.RoomResp", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: RoomResp): Int {
        var size = value.unknownFields.size
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.room_id)
        }
        if (value.room_info != null) {
          size += RoomInfo.ADAPTER.encodedSizeWithTag(2, value.room_info)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RoomResp) {
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
        if (value.room_info != null) {
          RoomInfo.ADAPTER.encodeWithTag(writer, 2, value.room_info)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RoomResp) {
        writer.writeBytes(value.unknownFields)
        if (value.room_info != null) {
          RoomInfo.ADAPTER.encodeWithTag(writer, 2, value.room_info)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
      }

      override fun decode(reader: ProtoReader): RoomResp {
        var room_id: String = ""
        var room_info: RoomInfo? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> room_id = ProtoAdapter.STRING.decode(reader)
            2 -> room_info = RoomInfo.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RoomResp(
          room_id = room_id,
          room_info = room_info,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RoomResp): RoomResp = value.copy(
        room_info = value.room_info?.let(RoomInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
