// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.RoomInfo in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class RoomInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 0,
  )
  public val room_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ownerId",
    schemaIndex = 1,
  )
  public val owner_id: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "maxPlayers",
    schemaIndex = 2,
  )
  public val max_players: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currentPlayers",
    schemaIndex = 3,
  )
  public val current_players: Int = 0,
  players: List<RoomPlayer> = emptyList(),
  /**
   * 0: Waiting, 1: Playing
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val status: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RoomInfo, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 5,
    adapter = "com.sudooom.mahjong.common.proto.RoomPlayer#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val players: List<RoomPlayer> = immutableCopyOf("players", players)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RoomInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (room_id != other.room_id) return false
    if (owner_id != other.owner_id) return false
    if (max_players != other.max_players) return false
    if (current_players != other.current_players) return false
    if (players != other.players) return false
    if (status != other.status) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + owner_id.hashCode()
      result = result * 37 + max_players.hashCode()
      result = result * 37 + current_players.hashCode()
      result = result * 37 + players.hashCode()
      result = result * 37 + status.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """room_id=${sanitize(room_id)}"""
    result += """owner_id=${sanitize(owner_id)}"""
    result += """max_players=$max_players"""
    result += """current_players=$current_players"""
    if (players.isNotEmpty()) result += """players=$players"""
    result += """status=$status"""
    return result.joinToString(prefix = "RoomInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    room_id: String = this.room_id,
    owner_id: String = this.owner_id,
    max_players: Int = this.max_players,
    current_players: Int = this.current_players,
    players: List<RoomPlayer> = this.players,
    status: Int = this.status,
    unknownFields: ByteString = this.unknownFields,
  ): RoomInfo = RoomInfo(room_id, owner_id, max_players, current_players, players, status, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RoomInfo> = object : ProtoAdapter<RoomInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      RoomInfo::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.RoomInfo", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: RoomInfo): Int {
        var size = value.unknownFields.size
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.room_id)
        }
        if (value.owner_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.owner_id)
        }
        if (value.max_players != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.max_players)
        }
        if (value.current_players != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.current_players)
        }
        size += RoomPlayer.ADAPTER.asRepeated().encodedSizeWithTag(5, value.players)
        if (value.status != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.status)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RoomInfo) {
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
        if (value.owner_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.owner_id)
        }
        if (value.max_players != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.max_players)
        }
        if (value.current_players != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.current_players)
        }
        RoomPlayer.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.players)
        if (value.status != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.status)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RoomInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.status != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 6, value.status)
        }
        RoomPlayer.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.players)
        if (value.current_players != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.current_players)
        }
        if (value.max_players != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.max_players)
        }
        if (value.owner_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.owner_id)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.room_id)
        }
      }

      override fun decode(reader: ProtoReader): RoomInfo {
        var room_id: String = ""
        var owner_id: String = ""
        var max_players: Int = 0
        var current_players: Int = 0
        val players = mutableListOf<RoomPlayer>()
        var status: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> room_id = ProtoAdapter.STRING.decode(reader)
            2 -> owner_id = ProtoAdapter.STRING.decode(reader)
            3 -> max_players = ProtoAdapter.INT32.decode(reader)
            4 -> current_players = ProtoAdapter.INT32.decode(reader)
            5 -> players.add(RoomPlayer.ADAPTER.decode(reader))
            6 -> status = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RoomInfo(
          room_id = room_id,
          owner_id = owner_id,
          max_players = max_players,
          current_players = current_players,
          players = players,
          status = status,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RoomInfo): RoomInfo = value.copy(
        players = value.players.redactElements(RoomPlayer.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
