// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.RoomPlayer in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class RoomPlayer(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 0,
  )
  public val user_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.UserInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val user: UserInfo? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isReady",
    schemaIndex = 2,
  )
  public val is_ready: Boolean = false,
  /**
   * 0-3
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "seatIndex",
    schemaIndex = 3,
  )
  public val seat_index: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isOnline",
    schemaIndex = 4,
  )
  public val is_online: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RoomPlayer, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RoomPlayer) return false
    if (unknownFields != other.unknownFields) return false
    if (user_id != other.user_id) return false
    if (user != other.user) return false
    if (is_ready != other.is_ready) return false
    if (seat_index != other.seat_index) return false
    if (is_online != other.is_online) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + (user?.hashCode() ?: 0)
      result = result * 37 + is_ready.hashCode()
      result = result * 37 + seat_index.hashCode()
      result = result * 37 + is_online.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """user_id=${sanitize(user_id)}"""
    if (user != null) result += """user=$user"""
    result += """is_ready=$is_ready"""
    result += """seat_index=$seat_index"""
    result += """is_online=$is_online"""
    return result.joinToString(prefix = "RoomPlayer{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_id: String = this.user_id,
    user: UserInfo? = this.user,
    is_ready: Boolean = this.is_ready,
    seat_index: Int = this.seat_index,
    is_online: Boolean = this.is_online,
    unknownFields: ByteString = this.unknownFields,
  ): RoomPlayer = RoomPlayer(user_id, user, is_ready, seat_index, is_online, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RoomPlayer> = object : ProtoAdapter<RoomPlayer>(
      FieldEncoding.LENGTH_DELIMITED, 
      RoomPlayer::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.RoomPlayer", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: RoomPlayer): Int {
        var size = value.unknownFields.size
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id)
        }
        if (value.user != null) {
          size += UserInfo.ADAPTER.encodedSizeWithTag(2, value.user)
        }
        if (value.is_ready != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.is_ready)
        }
        if (value.seat_index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.seat_index)
        }
        if (value.is_online != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.is_online)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RoomPlayer) {
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
        if (value.user != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 2, value.user)
        }
        if (value.is_ready != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_ready)
        }
        if (value.seat_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.seat_index)
        }
        if (value.is_online != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.is_online)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RoomPlayer) {
        writer.writeBytes(value.unknownFields)
        if (value.is_online != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.is_online)
        }
        if (value.seat_index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.seat_index)
        }
        if (value.is_ready != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_ready)
        }
        if (value.user != null) {
          UserInfo.ADAPTER.encodeWithTag(writer, 2, value.user)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
      }

      override fun decode(reader: ProtoReader): RoomPlayer {
        var user_id: String = ""
        var user: UserInfo? = null
        var is_ready: Boolean = false
        var seat_index: Int = 0
        var is_online: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_id = ProtoAdapter.STRING.decode(reader)
            2 -> user = UserInfo.ADAPTER.decode(reader)
            3 -> is_ready = ProtoAdapter.BOOL.decode(reader)
            4 -> seat_index = ProtoAdapter.INT32.decode(reader)
            5 -> is_online = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RoomPlayer(
          user_id = user_id,
          user = user,
          is_ready = is_ready,
          seat_index = seat_index,
          is_online = is_online,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RoomPlayer): RoomPlayer = value.copy(
        user = value.user?.let(UserInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
