// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.RoomReq in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class RoomReq(
  @field:WireField(
    tag = 1,
    adapter = "com.sudooom.mahjong.common.proto.RoomReq${'$'}Action#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val action: Action = Action.CREATE,
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.GameType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "gameType",
    schemaIndex = 1,
  )
  public val game_type: GameType = GameType.GAME_TYPE_UNKNOWN,
  /**
   * Join/Leave/Ready 时需要
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomId",
    schemaIndex = 2,
  )
  public val room_id: String = "",
  /**
   * Create 时需要 (JSON)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "roomConfig",
    schemaIndex = 3,
  )
  public val room_config: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RoomReq, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RoomReq) return false
    if (unknownFields != other.unknownFields) return false
    if (action != other.action) return false
    if (game_type != other.game_type) return false
    if (room_id != other.room_id) return false
    if (room_config != other.room_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + action.hashCode()
      result = result * 37 + game_type.hashCode()
      result = result * 37 + room_id.hashCode()
      result = result * 37 + room_config.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """action=$action"""
    result += """game_type=$game_type"""
    result += """room_id=${sanitize(room_id)}"""
    result += """room_config=${sanitize(room_config)}"""
    return result.joinToString(prefix = "RoomReq{", separator = ", ", postfix = "}")
  }

  public fun copy(
    action: Action = this.action,
    game_type: GameType = this.game_type,
    room_id: String = this.room_id,
    room_config: String = this.room_config,
    unknownFields: ByteString = this.unknownFields,
  ): RoomReq = RoomReq(action, game_type, room_id, room_config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RoomReq> = object : ProtoAdapter<RoomReq>(
      FieldEncoding.LENGTH_DELIMITED, 
      RoomReq::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.RoomReq", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: RoomReq): Int {
        var size = value.unknownFields.size
        if (value.action != com.sudooom.mahjong.common.proto.RoomReq.Action.CREATE) {
          size += Action.ADAPTER.encodedSizeWithTag(1, value.action)
        }
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          size += GameType.ADAPTER.encodedSizeWithTag(2, value.game_type)
        }
        if (value.room_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.room_id)
        }
        if (value.room_config != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.room_config)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RoomReq) {
        if (value.action != com.sudooom.mahjong.common.proto.RoomReq.Action.CREATE) {
          Action.ADAPTER.encodeWithTag(writer, 1, value.action)
        }
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          GameType.ADAPTER.encodeWithTag(writer, 2, value.game_type)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.room_id)
        }
        if (value.room_config != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.room_config)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RoomReq) {
        writer.writeBytes(value.unknownFields)
        if (value.room_config != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.room_config)
        }
        if (value.room_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.room_id)
        }
        if (value.game_type != com.sudooom.mahjong.common.proto.GameType.GAME_TYPE_UNKNOWN) {
          GameType.ADAPTER.encodeWithTag(writer, 2, value.game_type)
        }
        if (value.action != com.sudooom.mahjong.common.proto.RoomReq.Action.CREATE) {
          Action.ADAPTER.encodeWithTag(writer, 1, value.action)
        }
      }

      override fun decode(reader: ProtoReader): RoomReq {
        var action: Action = Action.CREATE
        var game_type: GameType = GameType.GAME_TYPE_UNKNOWN
        var room_id: String = ""
        var room_config: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              action = Action.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> try {
              game_type = GameType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> room_id = ProtoAdapter.STRING.decode(reader)
            4 -> room_config = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RoomReq(
          action = action,
          game_type = game_type,
          room_id = room_id,
          room_config = room_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RoomReq): RoomReq = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Action(
    override val `value`: Int,
  ) : WireEnum {
    CREATE(0),
    JOIN(1),
    LEAVE(2),
    READY(3),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Action> = object : EnumAdapter<Action>(
        Action::class, 
        PROTO_3, 
        Action.CREATE
      ) {
        override fun fromValue(`value`: Int): Action? = Action.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Action? = when (`value`) {
        0 -> CREATE
        1 -> JOIN
        2 -> LEAVE
        3 -> READY
        else -> null
      }
    }
  }
}
