// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.ServerMessage in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * Server Message (Internal Service Communication)
 * 消息结构设计:
 * 1. ServerMessage: 顶层路由消息，只有两个方向 (Access <-> Logic)
 * 2. 每个方向包含三类消息:
 *    - UserMessage: 涉及用户的业务消息 (聊天、游戏等)
 *    - MsgAck: 消息确认
 *    - SystemCommand: 系统指令 (上下线、踢人等)
 * =============================================================================
 * 顶层路由消息 - Access 和 Logic 之间的双向通信
 */
public class ServerMessage(
  /**
   * 链路追踪ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "traceId",
    schemaIndex = 0,
  )
  public val trace_id: String = "",
  /**
   * e.g., "logic-1", "access-2"
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "fromService",
    schemaIndex = 1,
  )
  public val from_service: String = "",
  /**
   * e.g., "access-2", "logic-1"
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "toService",
    schemaIndex = 2,
  )
  public val to_service: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val timestamp: Long = 0L,
  /**
   * Access -> Logic 方向的消息
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.AccessToLogicMsg#ADAPTER",
    jsonName = "accessToLogic",
    oneofName = "payload",
    schemaIndex = 4,
  )
  public val access_to_logic: AccessToLogicMsg? = null,
  /**
   * Logic -> Access 方向的消息
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.LogicToAccessMsg#ADAPTER",
    jsonName = "logicToAccess",
    oneofName = "payload",
    schemaIndex = 5,
  )
  public val logic_to_access: LogicToAccessMsg? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ServerMessage, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(access_to_logic, logic_to_access) <= 1) {
      "At most one of access_to_logic, logic_to_access may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ServerMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (trace_id != other.trace_id) return false
    if (from_service != other.from_service) return false
    if (to_service != other.to_service) return false
    if (timestamp != other.timestamp) return false
    if (access_to_logic != other.access_to_logic) return false
    if (logic_to_access != other.logic_to_access) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + trace_id.hashCode()
      result = result * 37 + from_service.hashCode()
      result = result * 37 + to_service.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + (access_to_logic?.hashCode() ?: 0)
      result = result * 37 + (logic_to_access?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """trace_id=${sanitize(trace_id)}"""
    result += """from_service=${sanitize(from_service)}"""
    result += """to_service=${sanitize(to_service)}"""
    result += """timestamp=$timestamp"""
    if (access_to_logic != null) result += """access_to_logic=$access_to_logic"""
    if (logic_to_access != null) result += """logic_to_access=$logic_to_access"""
    return result.joinToString(prefix = "ServerMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    trace_id: String = this.trace_id,
    from_service: String = this.from_service,
    to_service: String = this.to_service,
    timestamp: Long = this.timestamp,
    access_to_logic: AccessToLogicMsg? = this.access_to_logic,
    logic_to_access: LogicToAccessMsg? = this.logic_to_access,
    unknownFields: ByteString = this.unknownFields,
  ): ServerMessage = ServerMessage(trace_id, from_service, to_service, timestamp, access_to_logic, logic_to_access, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ServerMessage> = object : ProtoAdapter<ServerMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      ServerMessage::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.ServerMessage", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: ServerMessage): Int {
        var size = value.unknownFields.size
        if (value.trace_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.trace_id)
        }
        if (value.from_service != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.from_service)
        }
        if (value.to_service != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.to_service)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.timestamp)
        }
        size += AccessToLogicMsg.ADAPTER.encodedSizeWithTag(10, value.access_to_logic)
        size += LogicToAccessMsg.ADAPTER.encodedSizeWithTag(11, value.logic_to_access)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ServerMessage) {
        if (value.trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.trace_id)
        }
        if (value.from_service != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.from_service)
        }
        if (value.to_service != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.to_service)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.timestamp)
        }
        AccessToLogicMsg.ADAPTER.encodeWithTag(writer, 10, value.access_to_logic)
        LogicToAccessMsg.ADAPTER.encodeWithTag(writer, 11, value.logic_to_access)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ServerMessage) {
        writer.writeBytes(value.unknownFields)
        LogicToAccessMsg.ADAPTER.encodeWithTag(writer, 11, value.logic_to_access)
        AccessToLogicMsg.ADAPTER.encodeWithTag(writer, 10, value.access_to_logic)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.timestamp)
        }
        if (value.to_service != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.to_service)
        }
        if (value.from_service != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.from_service)
        }
        if (value.trace_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.trace_id)
        }
      }

      override fun decode(reader: ProtoReader): ServerMessage {
        var trace_id: String = ""
        var from_service: String = ""
        var to_service: String = ""
        var timestamp: Long = 0L
        var access_to_logic: AccessToLogicMsg? = null
        var logic_to_access: LogicToAccessMsg? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> trace_id = ProtoAdapter.STRING.decode(reader)
            2 -> from_service = ProtoAdapter.STRING.decode(reader)
            3 -> to_service = ProtoAdapter.STRING.decode(reader)
            4 -> timestamp = ProtoAdapter.INT64.decode(reader)
            10 -> access_to_logic = AccessToLogicMsg.ADAPTER.decode(reader)
            11 -> logic_to_access = LogicToAccessMsg.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ServerMessage(
          trace_id = trace_id,
          from_service = from_service,
          to_service = to_service,
          timestamp = timestamp,
          access_to_logic = access_to_logic,
          logic_to_access = logic_to_access,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ServerMessage): ServerMessage = value.copy(
        access_to_logic = value.access_to_logic?.let(AccessToLogicMsg.ADAPTER::redact),
        logic_to_access = value.logic_to_access?.let(LogicToAccessMsg.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
