// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.SystemCommand in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ========== 3. 系统指令 ==========
 */
public class SystemCommand(
  /**
   * 指令ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "cmdId",
    schemaIndex = 0,
  )
  public val cmd_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.SystemCommand${'$'}CommandType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "cmdType",
    schemaIndex = 1,
  )
  public val cmd_type: CommandType = CommandType.USER_ONLINE,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val timestamp: Long = 0L,
  /**
   * 用户上下线
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.UserOnlineOffline#ADAPTER",
    jsonName = "userStatus",
    oneofName = "command_data",
    schemaIndex = 3,
  )
  public val user_status: UserOnlineOffline? = null,
  /**
   * 踢用户
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.KickUser#ADAPTER",
    jsonName = "kickUser",
    oneofName = "command_data",
    schemaIndex = 4,
  )
  public val kick_user: KickUser? = null,
  /**
   * 广播
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.BroadcastCommand#ADAPTER",
    oneofName = "command_data",
    schemaIndex = 5,
  )
  public val broadcast: BroadcastCommand? = null,
  /**
   * 补偿
   */
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.CompensationCommand#ADAPTER",
    oneofName = "command_data",
    schemaIndex = 6,
  )
  public val compensation: CompensationCommand? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SystemCommand, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(user_status, kick_user, broadcast, compensation) <= 1) {
      "At most one of user_status, kick_user, broadcast, compensation may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SystemCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (cmd_id != other.cmd_id) return false
    if (cmd_type != other.cmd_type) return false
    if (timestamp != other.timestamp) return false
    if (user_status != other.user_status) return false
    if (kick_user != other.kick_user) return false
    if (broadcast != other.broadcast) return false
    if (compensation != other.compensation) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + cmd_id.hashCode()
      result = result * 37 + cmd_type.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + (user_status?.hashCode() ?: 0)
      result = result * 37 + (kick_user?.hashCode() ?: 0)
      result = result * 37 + (broadcast?.hashCode() ?: 0)
      result = result * 37 + (compensation?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """cmd_id=${sanitize(cmd_id)}"""
    result += """cmd_type=$cmd_type"""
    result += """timestamp=$timestamp"""
    if (user_status != null) result += """user_status=$user_status"""
    if (kick_user != null) result += """kick_user=$kick_user"""
    if (broadcast != null) result += """broadcast=$broadcast"""
    if (compensation != null) result += """compensation=$compensation"""
    return result.joinToString(prefix = "SystemCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(
    cmd_id: String = this.cmd_id,
    cmd_type: CommandType = this.cmd_type,
    timestamp: Long = this.timestamp,
    user_status: UserOnlineOffline? = this.user_status,
    kick_user: KickUser? = this.kick_user,
    broadcast: BroadcastCommand? = this.broadcast,
    compensation: CompensationCommand? = this.compensation,
    unknownFields: ByteString = this.unknownFields,
  ): SystemCommand = SystemCommand(cmd_id, cmd_type, timestamp, user_status, kick_user, broadcast, compensation, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SystemCommand> = object : ProtoAdapter<SystemCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      SystemCommand::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.SystemCommand", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: SystemCommand): Int {
        var size = value.unknownFields.size
        if (value.cmd_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.cmd_id)
        }
        if (value.cmd_type != com.sudooom.mahjong.common.proto.SystemCommand.CommandType.USER_ONLINE) {
          size += CommandType.ADAPTER.encodedSizeWithTag(2, value.cmd_type)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(3, value.timestamp)
        }
        size += UserOnlineOffline.ADAPTER.encodedSizeWithTag(10, value.user_status)
        size += KickUser.ADAPTER.encodedSizeWithTag(11, value.kick_user)
        size += BroadcastCommand.ADAPTER.encodedSizeWithTag(12, value.broadcast)
        size += CompensationCommand.ADAPTER.encodedSizeWithTag(13, value.compensation)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SystemCommand) {
        if (value.cmd_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.cmd_id)
        }
        if (value.cmd_type != com.sudooom.mahjong.common.proto.SystemCommand.CommandType.USER_ONLINE) {
          CommandType.ADAPTER.encodeWithTag(writer, 2, value.cmd_type)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.timestamp)
        }
        UserOnlineOffline.ADAPTER.encodeWithTag(writer, 10, value.user_status)
        KickUser.ADAPTER.encodeWithTag(writer, 11, value.kick_user)
        BroadcastCommand.ADAPTER.encodeWithTag(writer, 12, value.broadcast)
        CompensationCommand.ADAPTER.encodeWithTag(writer, 13, value.compensation)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SystemCommand) {
        writer.writeBytes(value.unknownFields)
        CompensationCommand.ADAPTER.encodeWithTag(writer, 13, value.compensation)
        BroadcastCommand.ADAPTER.encodeWithTag(writer, 12, value.broadcast)
        KickUser.ADAPTER.encodeWithTag(writer, 11, value.kick_user)
        UserOnlineOffline.ADAPTER.encodeWithTag(writer, 10, value.user_status)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 3, value.timestamp)
        }
        if (value.cmd_type != com.sudooom.mahjong.common.proto.SystemCommand.CommandType.USER_ONLINE) {
          CommandType.ADAPTER.encodeWithTag(writer, 2, value.cmd_type)
        }
        if (value.cmd_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.cmd_id)
        }
      }

      override fun decode(reader: ProtoReader): SystemCommand {
        var cmd_id: String = ""
        var cmd_type: CommandType = CommandType.USER_ONLINE
        var timestamp: Long = 0L
        var user_status: UserOnlineOffline? = null
        var kick_user: KickUser? = null
        var broadcast: BroadcastCommand? = null
        var compensation: CompensationCommand? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> cmd_id = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              cmd_type = CommandType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> timestamp = ProtoAdapter.INT64.decode(reader)
            10 -> user_status = UserOnlineOffline.ADAPTER.decode(reader)
            11 -> kick_user = KickUser.ADAPTER.decode(reader)
            12 -> broadcast = BroadcastCommand.ADAPTER.decode(reader)
            13 -> compensation = CompensationCommand.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SystemCommand(
          cmd_id = cmd_id,
          cmd_type = cmd_type,
          timestamp = timestamp,
          user_status = user_status,
          kick_user = kick_user,
          broadcast = broadcast,
          compensation = compensation,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SystemCommand): SystemCommand = value.copy(
        user_status = value.user_status?.let(UserOnlineOffline.ADAPTER::redact),
        kick_user = value.kick_user?.let(KickUser.ADAPTER::redact),
        broadcast = value.broadcast?.let(BroadcastCommand.ADAPTER::redact),
        compensation = value.compensation?.let(CompensationCommand.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class CommandType(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * Access -> Logic 的指令
     * 用户上线
     */
    USER_ONLINE(0),
    /**
     * 用户下线
     */
    USER_OFFLINE(1),
    /**
     * Logic -> Access 的指令
     * 踢用户下线
     */
    KICK_USER(10),
    /**
     * 广播消息
     */
    BROADCAST(11),
    /**
     * 双向指令
     * 补偿操作
     */
    COMPENSATION(20),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<CommandType> = object : EnumAdapter<CommandType>(
        CommandType::class, 
        PROTO_3, 
        CommandType.USER_ONLINE
      ) {
        override fun fromValue(`value`: Int): CommandType? = CommandType.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): CommandType? = when (`value`) {
        0 -> USER_ONLINE
        1 -> USER_OFFLINE
        10 -> KICK_USER
        11 -> BROADCAST
        20 -> COMPENSATION
        else -> null
      }
    }
  }
}
