// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.SystemPush in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class SystemPush(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val title: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val content: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.sudooom.mahjong.common.proto.SystemPush${'$'}Level#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val level: Level = Level.INFO,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "actionUrl",
    schemaIndex = 3,
  )
  public val action_url: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SystemPush, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SystemPush) return false
    if (unknownFields != other.unknownFields) return false
    if (title != other.title) return false
    if (content != other.content) return false
    if (level != other.level) return false
    if (action_url != other.action_url) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + title.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + level.hashCode()
      result = result * 37 + action_url.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """title=${sanitize(title)}"""
    result += """content=${sanitize(content)}"""
    result += """level=$level"""
    result += """action_url=${sanitize(action_url)}"""
    return result.joinToString(prefix = "SystemPush{", separator = ", ", postfix = "}")
  }

  public fun copy(
    title: String = this.title,
    content: String = this.content,
    level: Level = this.level,
    action_url: String = this.action_url,
    unknownFields: ByteString = this.unknownFields,
  ): SystemPush = SystemPush(title, content, level, action_url, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SystemPush> = object : ProtoAdapter<SystemPush>(
      FieldEncoding.LENGTH_DELIMITED, 
      SystemPush::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.SystemPush", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: SystemPush): Int {
        var size = value.unknownFields.size
        if (value.title != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.title)
        }
        if (value.content != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.content)
        }
        if (value.level != com.sudooom.mahjong.common.proto.SystemPush.Level.INFO) {
          size += Level.ADAPTER.encodedSizeWithTag(3, value.level)
        }
        if (value.action_url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.action_url)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SystemPush) {
        if (value.title != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.title)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content)
        }
        if (value.level != com.sudooom.mahjong.common.proto.SystemPush.Level.INFO) {
          Level.ADAPTER.encodeWithTag(writer, 3, value.level)
        }
        if (value.action_url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.action_url)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SystemPush) {
        writer.writeBytes(value.unknownFields)
        if (value.action_url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.action_url)
        }
        if (value.level != com.sudooom.mahjong.common.proto.SystemPush.Level.INFO) {
          Level.ADAPTER.encodeWithTag(writer, 3, value.level)
        }
        if (value.content != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content)
        }
        if (value.title != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.title)
        }
      }

      override fun decode(reader: ProtoReader): SystemPush {
        var title: String = ""
        var content: String = ""
        var level: Level = Level.INFO
        var action_url: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> title = ProtoAdapter.STRING.decode(reader)
            2 -> content = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              level = Level.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> action_url = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SystemPush(
          title = title,
          content = content,
          level = level,
          action_url = action_url,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SystemPush): SystemPush = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Level(
    override val `value`: Int,
  ) : WireEnum {
    INFO(0),
    WARNING(1),
    ERROR(2),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Level> = object : EnumAdapter<Level>(
        Level::class, 
        PROTO_3, 
        Level.INFO
      ) {
        override fun fromValue(`value`: Int): Level? = Level.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Level? = when (`value`) {
        0 -> INFO
        1 -> WARNING
        2 -> ERROR
        else -> null
      }
    }
  }
}
