// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.UserOnlineOffline in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * 用户上下线指令
 */
public class UserOnlineOffline(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 0,
  )
  public val user_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.sudooom.mahjong.common.proto.UserOnlineOffline${'$'}Status#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val status: Status = Status.ONLINE,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "gatewayId",
    schemaIndex = 2,
  )
  public val gateway_id: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceId",
    schemaIndex = 3,
  )
  public val device_id: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.sudooom.mahjong.common.proto.Platform#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val platform: Platform = Platform.PLATFORM_UNKNOWN,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val timestamp: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UserOnlineOffline, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserOnlineOffline) return false
    if (unknownFields != other.unknownFields) return false
    if (user_id != other.user_id) return false
    if (status != other.status) return false
    if (gateway_id != other.gateway_id) return false
    if (device_id != other.device_id) return false
    if (platform != other.platform) return false
    if (timestamp != other.timestamp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + gateway_id.hashCode()
      result = result * 37 + device_id.hashCode()
      result = result * 37 + platform.hashCode()
      result = result * 37 + timestamp.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """user_id=${sanitize(user_id)}"""
    result += """status=$status"""
    result += """gateway_id=${sanitize(gateway_id)}"""
    result += """device_id=${sanitize(device_id)}"""
    result += """platform=$platform"""
    result += """timestamp=$timestamp"""
    return result.joinToString(prefix = "UserOnlineOffline{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_id: String = this.user_id,
    status: Status = this.status,
    gateway_id: String = this.gateway_id,
    device_id: String = this.device_id,
    platform: Platform = this.platform,
    timestamp: Long = this.timestamp,
    unknownFields: ByteString = this.unknownFields,
  ): UserOnlineOffline = UserOnlineOffline(user_id, status, gateway_id, device_id, platform, timestamp, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserOnlineOffline> = object : ProtoAdapter<UserOnlineOffline>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserOnlineOffline::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.UserOnlineOffline", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: UserOnlineOffline): Int {
        var size = value.unknownFields.size
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id)
        }
        if (value.status != com.sudooom.mahjong.common.proto.UserOnlineOffline.Status.ONLINE) {
          size += Status.ADAPTER.encodedSizeWithTag(2, value.status)
        }
        if (value.gateway_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.gateway_id)
        }
        if (value.device_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.device_id)
        }
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          size += Platform.ADAPTER.encodedSizeWithTag(5, value.platform)
        }
        if (value.timestamp != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(6, value.timestamp)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserOnlineOffline) {
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
        if (value.status != com.sudooom.mahjong.common.proto.UserOnlineOffline.Status.ONLINE) {
          Status.ADAPTER.encodeWithTag(writer, 2, value.status)
        }
        if (value.gateway_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.gateway_id)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.device_id)
        }
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          Platform.ADAPTER.encodeWithTag(writer, 5, value.platform)
        }
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.timestamp)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserOnlineOffline) {
        writer.writeBytes(value.unknownFields)
        if (value.timestamp != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 6, value.timestamp)
        }
        if (value.platform != com.sudooom.mahjong.common.proto.Platform.PLATFORM_UNKNOWN) {
          Platform.ADAPTER.encodeWithTag(writer, 5, value.platform)
        }
        if (value.device_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.device_id)
        }
        if (value.gateway_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.gateway_id)
        }
        if (value.status != com.sudooom.mahjong.common.proto.UserOnlineOffline.Status.ONLINE) {
          Status.ADAPTER.encodeWithTag(writer, 2, value.status)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
      }

      override fun decode(reader: ProtoReader): UserOnlineOffline {
        var user_id: String = ""
        var status: Status = Status.ONLINE
        var gateway_id: String = ""
        var device_id: String = ""
        var platform: Platform = Platform.PLATFORM_UNKNOWN
        var timestamp: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_id = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              status = Status.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> gateway_id = ProtoAdapter.STRING.decode(reader)
            4 -> device_id = ProtoAdapter.STRING.decode(reader)
            5 -> try {
              platform = Platform.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            6 -> timestamp = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserOnlineOffline(
          user_id = user_id,
          status = status,
          gateway_id = gateway_id,
          device_id = device_id,
          platform = platform,
          timestamp = timestamp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserOnlineOffline): UserOnlineOffline = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Status(
    override val `value`: Int,
  ) : WireEnum {
    ONLINE(0),
    OFFLINE(1),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Status> = object : EnumAdapter<Status>(
        Status::class, 
        PROTO_3, 
        Status.ONLINE
      ) {
        override fun fromValue(`value`: Int): Status? = Status.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Status? = when (`value`) {
        0 -> ONLINE
        1 -> OFFLINE
        else -> null
      }
    }
  }
}
