// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.UserMessagePush in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Logic -> Access: 推送给用户的业务消息
 */
public class UserMessagePush(
  target_user_ids: List<String> = emptyList(),
  /**
   * 消息ID
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgId",
    schemaIndex = 1,
  )
  public val msg_id: String = "",
  /**
   * 是否需要 ACK
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requireAck",
    schemaIndex = 2,
  )
  public val require_ack: Boolean = false,
  /**
   * 聊天推送
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.ChatPush#ADAPTER",
    jsonName = "chatPush",
    oneofName = "message_type",
    schemaIndex = 3,
  )
  public val chat_push: ChatPush? = null,
  /**
   * 游戏推送
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.GamePush#ADAPTER",
    jsonName = "gamePush",
    oneofName = "message_type",
    schemaIndex = 4,
  )
  public val game_push: GamePush? = null,
  /**
   * 房间推送
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.RoomPush#ADAPTER",
    jsonName = "roomPush",
    oneofName = "message_type",
    schemaIndex = 5,
  )
  public val room_push: RoomPush? = null,
  /**
   * 系统推送
   */
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.SystemPush#ADAPTER",
    jsonName = "systemPush",
    oneofName = "message_type",
    schemaIndex = 6,
  )
  public val system_push: SystemPush? = null,
  /**
   * 聊天发送确认
   */
  @field:WireField(
    tag = 14,
    adapter = "com.sudooom.mahjong.common.proto.ChatSendAck#ADAPTER",
    jsonName = "chatAck",
    oneofName = "message_type",
    schemaIndex = 7,
  )
  public val chat_ack: ChatSendAck? = null,
  /**
   * 房间操作响应
   */
  @field:WireField(
    tag = 15,
    adapter = "com.sudooom.mahjong.common.proto.RoomResp#ADAPTER",
    jsonName = "roomResp",
    oneofName = "message_type",
    schemaIndex = 8,
  )
  public val room_resp: RoomResp? = null,
  /**
   * 心跳响应
   */
  @field:WireField(
    tag = 16,
    adapter = "com.sudooom.mahjong.common.proto.HeartbeatResp#ADAPTER",
    jsonName = "heartbeatResp",
    oneofName = "message_type",
    schemaIndex = 9,
  )
  public val heartbeat_resp: HeartbeatResp? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UserMessagePush, Nothing>(ADAPTER, unknownFields) {
  /**
   * 目标用户列表
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "targetUserIds",
    schemaIndex = 0,
  )
  public val target_user_ids: List<String> = immutableCopyOf("target_user_ids", target_user_ids)

  init {
    require(countNonNull(chat_push, game_push, room_push, system_push, chat_ack, room_resp, heartbeat_resp) <= 1) {
      "At most one of chat_push, game_push, room_push, system_push, chat_ack, room_resp, heartbeat_resp may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserMessagePush) return false
    if (unknownFields != other.unknownFields) return false
    if (target_user_ids != other.target_user_ids) return false
    if (msg_id != other.msg_id) return false
    if (require_ack != other.require_ack) return false
    if (chat_push != other.chat_push) return false
    if (game_push != other.game_push) return false
    if (room_push != other.room_push) return false
    if (system_push != other.system_push) return false
    if (chat_ack != other.chat_ack) return false
    if (room_resp != other.room_resp) return false
    if (heartbeat_resp != other.heartbeat_resp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + target_user_ids.hashCode()
      result = result * 37 + msg_id.hashCode()
      result = result * 37 + require_ack.hashCode()
      result = result * 37 + (chat_push?.hashCode() ?: 0)
      result = result * 37 + (game_push?.hashCode() ?: 0)
      result = result * 37 + (room_push?.hashCode() ?: 0)
      result = result * 37 + (system_push?.hashCode() ?: 0)
      result = result * 37 + (chat_ack?.hashCode() ?: 0)
      result = result * 37 + (room_resp?.hashCode() ?: 0)
      result = result * 37 + (heartbeat_resp?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (target_user_ids.isNotEmpty()) result += """target_user_ids=${sanitize(target_user_ids)}"""
    result += """msg_id=${sanitize(msg_id)}"""
    result += """require_ack=$require_ack"""
    if (chat_push != null) result += """chat_push=$chat_push"""
    if (game_push != null) result += """game_push=$game_push"""
    if (room_push != null) result += """room_push=$room_push"""
    if (system_push != null) result += """system_push=$system_push"""
    if (chat_ack != null) result += """chat_ack=$chat_ack"""
    if (room_resp != null) result += """room_resp=$room_resp"""
    if (heartbeat_resp != null) result += """heartbeat_resp=$heartbeat_resp"""
    return result.joinToString(prefix = "UserMessagePush{", separator = ", ", postfix = "}")
  }

  public fun copy(
    target_user_ids: List<String> = this.target_user_ids,
    msg_id: String = this.msg_id,
    require_ack: Boolean = this.require_ack,
    chat_push: ChatPush? = this.chat_push,
    game_push: GamePush? = this.game_push,
    room_push: RoomPush? = this.room_push,
    system_push: SystemPush? = this.system_push,
    chat_ack: ChatSendAck? = this.chat_ack,
    room_resp: RoomResp? = this.room_resp,
    heartbeat_resp: HeartbeatResp? = this.heartbeat_resp,
    unknownFields: ByteString = this.unknownFields,
  ): UserMessagePush = UserMessagePush(target_user_ids, msg_id, require_ack, chat_push, game_push, room_push, system_push, chat_ack, room_resp, heartbeat_resp, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserMessagePush> = object : ProtoAdapter<UserMessagePush>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserMessagePush::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.UserMessagePush", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: UserMessagePush): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.target_user_ids)
        if (value.msg_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.msg_id)
        }
        if (value.require_ack != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.require_ack)
        }
        size += ChatPush.ADAPTER.encodedSizeWithTag(10, value.chat_push)
        size += GamePush.ADAPTER.encodedSizeWithTag(11, value.game_push)
        size += RoomPush.ADAPTER.encodedSizeWithTag(12, value.room_push)
        size += SystemPush.ADAPTER.encodedSizeWithTag(13, value.system_push)
        size += ChatSendAck.ADAPTER.encodedSizeWithTag(14, value.chat_ack)
        size += RoomResp.ADAPTER.encodedSizeWithTag(15, value.room_resp)
        size += HeartbeatResp.ADAPTER.encodedSizeWithTag(16, value.heartbeat_resp)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserMessagePush) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.target_user_ids)
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.msg_id)
        }
        if (value.require_ack != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.require_ack)
        }
        ChatPush.ADAPTER.encodeWithTag(writer, 10, value.chat_push)
        GamePush.ADAPTER.encodeWithTag(writer, 11, value.game_push)
        RoomPush.ADAPTER.encodeWithTag(writer, 12, value.room_push)
        SystemPush.ADAPTER.encodeWithTag(writer, 13, value.system_push)
        ChatSendAck.ADAPTER.encodeWithTag(writer, 14, value.chat_ack)
        RoomResp.ADAPTER.encodeWithTag(writer, 15, value.room_resp)
        HeartbeatResp.ADAPTER.encodeWithTag(writer, 16, value.heartbeat_resp)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserMessagePush) {
        writer.writeBytes(value.unknownFields)
        HeartbeatResp.ADAPTER.encodeWithTag(writer, 16, value.heartbeat_resp)
        RoomResp.ADAPTER.encodeWithTag(writer, 15, value.room_resp)
        ChatSendAck.ADAPTER.encodeWithTag(writer, 14, value.chat_ack)
        SystemPush.ADAPTER.encodeWithTag(writer, 13, value.system_push)
        RoomPush.ADAPTER.encodeWithTag(writer, 12, value.room_push)
        GamePush.ADAPTER.encodeWithTag(writer, 11, value.game_push)
        ChatPush.ADAPTER.encodeWithTag(writer, 10, value.chat_push)
        if (value.require_ack != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.require_ack)
        }
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.msg_id)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.target_user_ids)
      }

      override fun decode(reader: ProtoReader): UserMessagePush {
        val target_user_ids = mutableListOf<String>()
        var msg_id: String = ""
        var require_ack: Boolean = false
        var chat_push: ChatPush? = null
        var game_push: GamePush? = null
        var room_push: RoomPush? = null
        var system_push: SystemPush? = null
        var chat_ack: ChatSendAck? = null
        var room_resp: RoomResp? = null
        var heartbeat_resp: HeartbeatResp? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> target_user_ids.add(ProtoAdapter.STRING.decode(reader))
            2 -> msg_id = ProtoAdapter.STRING.decode(reader)
            3 -> require_ack = ProtoAdapter.BOOL.decode(reader)
            10 -> chat_push = ChatPush.ADAPTER.decode(reader)
            11 -> game_push = GamePush.ADAPTER.decode(reader)
            12 -> room_push = RoomPush.ADAPTER.decode(reader)
            13 -> system_push = SystemPush.ADAPTER.decode(reader)
            14 -> chat_ack = ChatSendAck.ADAPTER.decode(reader)
            15 -> room_resp = RoomResp.ADAPTER.decode(reader)
            16 -> heartbeat_resp = HeartbeatResp.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserMessagePush(
          target_user_ids = target_user_ids,
          msg_id = msg_id,
          require_ack = require_ack,
          chat_push = chat_push,
          game_push = game_push,
          room_push = room_push,
          system_push = system_push,
          chat_ack = chat_ack,
          room_resp = room_resp,
          heartbeat_resp = heartbeat_resp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserMessagePush): UserMessagePush = value.copy(
        chat_push = value.chat_push?.let(ChatPush.ADAPTER::redact),
        game_push = value.game_push?.let(GamePush.ADAPTER::redact),
        room_push = value.room_push?.let(RoomPush.ADAPTER::redact),
        system_push = value.system_push?.let(SystemPush.ADAPTER::redact),
        chat_ack = value.chat_ack?.let(ChatSendAck.ADAPTER::redact),
        room_resp = value.room_resp?.let(RoomResp.ADAPTER::redact),
        heartbeat_resp = value.heartbeat_resp?.let(HeartbeatResp.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
