// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.UserInfo in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * Common Models
 * =============================================================================
 */
public class UserInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userId",
    schemaIndex = 0,
  )
  public val user_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val nickname: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val avatar: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val level: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val coins: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UserInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (user_id != other.user_id) return false
    if (nickname != other.nickname) return false
    if (avatar != other.avatar) return false
    if (level != other.level) return false
    if (coins != other.coins) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + user_id.hashCode()
      result = result * 37 + nickname.hashCode()
      result = result * 37 + avatar.hashCode()
      result = result * 37 + level.hashCode()
      result = result * 37 + coins.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """user_id=${sanitize(user_id)}"""
    result += """nickname=${sanitize(nickname)}"""
    result += """avatar=${sanitize(avatar)}"""
    result += """level=$level"""
    result += """coins=$coins"""
    return result.joinToString(prefix = "UserInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    user_id: String = this.user_id,
    nickname: String = this.nickname,
    avatar: String = this.avatar,
    level: Int = this.level,
    coins: Long = this.coins,
    unknownFields: ByteString = this.unknownFields,
  ): UserInfo = UserInfo(user_id, nickname, avatar, level, coins, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserInfo> = object : ProtoAdapter<UserInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserInfo::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.UserInfo", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: UserInfo): Int {
        var size = value.unknownFields.size
        if (value.user_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.user_id)
        }
        if (value.nickname != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.nickname)
        }
        if (value.avatar != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.avatar)
        }
        if (value.level != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.level)
        }
        if (value.coins != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(5, value.coins)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserInfo) {
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
        if (value.nickname != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.nickname)
        }
        if (value.avatar != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.avatar)
        }
        if (value.level != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.level)
        }
        if (value.coins != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 5, value.coins)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.coins != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 5, value.coins)
        }
        if (value.level != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.level)
        }
        if (value.avatar != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.avatar)
        }
        if (value.nickname != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.nickname)
        }
        if (value.user_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.user_id)
        }
      }

      override fun decode(reader: ProtoReader): UserInfo {
        var user_id: String = ""
        var nickname: String = ""
        var avatar: String = ""
        var level: Int = 0
        var coins: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> user_id = ProtoAdapter.STRING.decode(reader)
            2 -> nickname = ProtoAdapter.STRING.decode(reader)
            3 -> avatar = ProtoAdapter.STRING.decode(reader)
            4 -> level = ProtoAdapter.INT32.decode(reader)
            5 -> coins = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserInfo(
          user_id = user_id,
          nickname = nickname,
          avatar = avatar,
          level = level,
          coins = coins,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserInfo): UserInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
