// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.sudooom.mahjong.common.proto.UserMessage in message.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.sudooom.mahjong.common.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * =============================================================================
 * 消息类型定义
 * =============================================================================
 * ========== 1. 用户业务消息 ==========
 * Access -> Logic: 用户发起的业务消息
 */
public class UserMessage(
  /**
   * 消息ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "msgId",
    schemaIndex = 0,
  )
  public val msg_id: String = "",
  /**
   * 聊天消息
   */
  @field:WireField(
    tag = 10,
    adapter = "com.sudooom.mahjong.common.proto.ChatSendReq#ADAPTER",
    jsonName = "chatSend",
    oneofName = "message_type",
    schemaIndex = 1,
  )
  public val chat_send: ChatSendReq? = null,
  /**
   * 游戏请求
   */
  @field:WireField(
    tag = 11,
    adapter = "com.sudooom.mahjong.common.proto.GameReq#ADAPTER",
    jsonName = "gameReq",
    oneofName = "message_type",
    schemaIndex = 2,
  )
  public val game_req: GameReq? = null,
  /**
   * 房间操作
   */
  @field:WireField(
    tag = 12,
    adapter = "com.sudooom.mahjong.common.proto.RoomReq#ADAPTER",
    jsonName = "roomReq",
    oneofName = "message_type",
    schemaIndex = 3,
  )
  public val room_req: RoomReq? = null,
  /**
   * 心跳 (客户端心跳，不是服务端间心跳)
   */
  @field:WireField(
    tag = 13,
    adapter = "com.sudooom.mahjong.common.proto.HeartbeatReq#ADAPTER",
    oneofName = "message_type",
    schemaIndex = 4,
  )
  public val heartbeat: HeartbeatReq? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UserMessage, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(chat_send, game_req, room_req, heartbeat) <= 1) {
      "At most one of chat_send, game_req, room_req, heartbeat may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (msg_id != other.msg_id) return false
    if (chat_send != other.chat_send) return false
    if (game_req != other.game_req) return false
    if (room_req != other.room_req) return false
    if (heartbeat != other.heartbeat) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + msg_id.hashCode()
      result = result * 37 + (chat_send?.hashCode() ?: 0)
      result = result * 37 + (game_req?.hashCode() ?: 0)
      result = result * 37 + (room_req?.hashCode() ?: 0)
      result = result * 37 + (heartbeat?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """msg_id=${sanitize(msg_id)}"""
    if (chat_send != null) result += """chat_send=$chat_send"""
    if (game_req != null) result += """game_req=$game_req"""
    if (room_req != null) result += """room_req=$room_req"""
    if (heartbeat != null) result += """heartbeat=$heartbeat"""
    return result.joinToString(prefix = "UserMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    msg_id: String = this.msg_id,
    chat_send: ChatSendReq? = this.chat_send,
    game_req: GameReq? = this.game_req,
    room_req: RoomReq? = this.room_req,
    heartbeat: HeartbeatReq? = this.heartbeat,
    unknownFields: ByteString = this.unknownFields,
  ): UserMessage = UserMessage(msg_id, chat_send, game_req, room_req, heartbeat, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserMessage> = object : ProtoAdapter<UserMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserMessage::class, 
      "type.googleapis.com/com.sudooom.mahjong.common.proto.UserMessage", 
      PROTO_3, 
      null, 
      "message.proto"
    ) {
      override fun encodedSize(`value`: UserMessage): Int {
        var size = value.unknownFields.size
        if (value.msg_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.msg_id)
        }
        size += ChatSendReq.ADAPTER.encodedSizeWithTag(10, value.chat_send)
        size += GameReq.ADAPTER.encodedSizeWithTag(11, value.game_req)
        size += RoomReq.ADAPTER.encodedSizeWithTag(12, value.room_req)
        size += HeartbeatReq.ADAPTER.encodedSizeWithTag(13, value.heartbeat)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserMessage) {
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
        ChatSendReq.ADAPTER.encodeWithTag(writer, 10, value.chat_send)
        GameReq.ADAPTER.encodeWithTag(writer, 11, value.game_req)
        RoomReq.ADAPTER.encodeWithTag(writer, 12, value.room_req)
        HeartbeatReq.ADAPTER.encodeWithTag(writer, 13, value.heartbeat)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserMessage) {
        writer.writeBytes(value.unknownFields)
        HeartbeatReq.ADAPTER.encodeWithTag(writer, 13, value.heartbeat)
        RoomReq.ADAPTER.encodeWithTag(writer, 12, value.room_req)
        GameReq.ADAPTER.encodeWithTag(writer, 11, value.game_req)
        ChatSendReq.ADAPTER.encodeWithTag(writer, 10, value.chat_send)
        if (value.msg_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg_id)
        }
      }

      override fun decode(reader: ProtoReader): UserMessage {
        var msg_id: String = ""
        var chat_send: ChatSendReq? = null
        var game_req: GameReq? = null
        var room_req: RoomReq? = null
        var heartbeat: HeartbeatReq? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> msg_id = ProtoAdapter.STRING.decode(reader)
            10 -> chat_send = ChatSendReq.ADAPTER.decode(reader)
            11 -> game_req = GameReq.ADAPTER.decode(reader)
            12 -> room_req = RoomReq.ADAPTER.decode(reader)
            13 -> heartbeat = HeartbeatReq.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserMessage(
          msg_id = msg_id,
          chat_send = chat_send,
          game_req = game_req,
          room_req = room_req,
          heartbeat = heartbeat,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserMessage): UserMessage = value.copy(
        chat_send = value.chat_send?.let(ChatSendReq.ADAPTER::redact),
        game_req = value.game_req?.let(GameReq.ADAPTER::redact),
        room_req = value.room_req?.let(RoomReq.ADAPTER::redact),
        heartbeat = value.heartbeat?.let(HeartbeatReq.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
